import {ERRATA,BOOK_REFS} from "./data.js";
import {LESSONS} from "./catalog.js";
// Sintesi originali dei passaggi studiati. I PDF e gli esercizi del libro non
// vengono distribuiti con il sito. Numeri stampati e pagine PDF sono distinti.
const ox=(units,pages,note)=>({book:"OXFORD",units,pages,pdf_pages:pages,note_it:note});
const mission=(pages,note)=>({book:"MISSION",units:null,pages,pdf_pages:pages,note_it:note});
const target=(pages,note)=>({book:"TARGET",units:null,pages,pdf_pages:pages,note_it:note});
const camp=(pages,pdf_pages,note)=>({book:"CAMPAIGN",units:null,pages,pdf_pages,note_it:note});
const packs=[
  ["articles",ox("110-112","256-261","Scegli a/an quando introduci un elemento non identificato; the quando il riferimento è identificabile nel contesto. Per molte generalizzazioni con plurali o nomi non numerabili si omette l'articolo. Non trasferire automaticamente gli articoli italiani.")],
  ["prepositions",ox("126-128","288-293","Distingui posizione, movimento e riferimento temporale. At, on e in non sono traduzioni fisse delle preposizioni italiane: esercita luoghi, orari, giorni e periodi dentro frasi operative chiare.")],
  ["comparison",ox("147-148","332-335","Comparativi e superlativi confrontano opzioni e gruppi. Controlla -er/-est oppure more/most, le forme irregolari e il termine di confronto introdotto da than. Nel raccomandare una procedura fai esplicitare anche il criterio del confronto.")],
  ["clefts",ox("174","394-395","Le frasi scisse mettono in evidenza un elemento della frase. Conserva i fatti mentre cambi il fuoco informativo; non usare l'enfasi per aggiungere informazioni che non erano nella frase di partenza.")],
  ["argument nominalisation subjunctive",target("154-155","La scrittura complessa deve restare pertinente, strutturata e sostenuta da ragioni. Per la grammatica di nominalizzazioni e richieste formali usa le spiegazioni originali della lezione; queste pagine forniscono il metodo argomentativo, non un trattamento di ogni struttura avanzata.")],
  ["sentence pronouns adjectives",ox("5, 120, 150","24, 276, 338","Controlla il soggetto, l'accordo e la funzione dell'avverbio nella frase. Pronomi soggetto e complemento hanno funzioni diverse. Se il controllo iniziale è sicuro, passa all'applicazione nei tempi anziché ripetere le definizioni.")],
  ["present-simple present questions negatives",ox("5-6","24-27","Routine e situazioni considerate stabili: present simple. He/she/it richiede -s soltanto nell'affermativa; dopo does/doesn't resta la forma base. Domande: do/does + soggetto + forma base; negative: do/does not + forma base.")],
  ["present-continuous present",ox("9, 11","32, 36","Il continuous presenta un'attività in corso o temporanea: be + -ing. Non scegliere il tempo traducendo l'italiano parola per parola. Confronta abitudine e attività del periodo; molti verbi di stato normalmente restano al simple.")],
  ["past-simple negatives questions",ox("17-19","50-55","Un momento passato concluso richiede normalmente il past simple. Nelle domande e nelle negative did porta il passato: il verbo principale è alla forma base, anche se irregolare. Be usa was/were, senza did.")],
  ["past-continuous past",ox("21-22","58-61","Il past continuous mette in scena un'attività già in corso; il past simple può raccontare l'evento che interviene. Fai costruire il rapporto temporale e non una regola meccanica su una sola parola.")],
  ["past past-continuous reported",camp("33","29","Trasforma una testimonianza in narrazione in terza persona, chiarendo chi parla e chi compie ogni azione. Usa contesti originali con witness, victim e assailant, senza copiare la testimonianza del manuale.")],
  ["past past-continuous negatives",camp("51","47","Nel rapporto distingui data, luogo, attività in corso, evento accaduto e azioni successive. Allena insieme past continuous, past simple e negazioni. Inserisci lessico operativo spiegato, senza richiedere l'audio del libro.")],
  ["present-perfect-simple perfect-simple",ox("25, 28","68, 74-75","Have/has + participio collega il passato al presente; un momento finito come yesterday normalmente richiede il past simple. Il contesto deve chiarire risultato attuale e riferimento temporale, senza presumere che ogni passato italiano sia present perfect.")],
  ["present-perfect-continuous perfect-continuous",ox("30-31","78-81","Have/has been + -ing evidenzia l'attività prolungata o ripetuta. La forma semplice mette spesso in primo piano un risultato o un numero di eventi. In alcuni contesti entrambe sono valide: evita soluzioni uniche quando il significato non le impone.")],
  ["past-perfect-simple past-perfect",ox("33","84-85","Had + participio indica un evento anteriore a un riferimento passato. Non usarlo per tutti i verbi di un racconto: stabilisci prima quale momento funge da riferimento.")],
  ["past-perfect-continuous past-perfect",ox("34","86-87","Had been + -ing mette a fuoco l'attività o la sua durata prima di un riferimento passato, spesso per spiegare una conseguenza. Distingui durata e completamento.")],
  ["future-arrangements future",ox("36-37","92-95","Il present simple può riferirsi a un calendario o orario; il present continuous a un accordo organizzato. Going to può essere compatibile con un piano: non dichiararlo scorretto senza una consegna che imponga una forma.")],
  ["future-going-to future",ox("38","96-97","Be going to + forma base descrive piani o previsioni basate su elementi presenti. Confrontalo con una decisione presa durante la conversazione e accetta le sovrapposizioni plausibili con il present continuous.")],
  ["future-will future",ox("39-40","98-101","Will + forma base può esprimere decisioni spontanee, promesse o previsioni. La negativa è will not/won't; non usare do con will. La scelta rispetto a going to dipende da intenzione e contesto.")],
  ["future-continuous future-perfect future-perfect-simple future-perfect-continuous",ox("42","104-105","Will be + -ing: attività in corso a un riferimento futuro. Will have + participio: risultato o stato considerato da quel riferimento. Will have been + -ing evidenzia la durata; è meno frequente e non va forzato nei rapporti.")],
  ["clauses future future-perfect",ox("43","106-107","Nelle subordinate temporali sul futuro usa normalmente un presente dopo when, before o as soon as. Il present perfect può mettere a fuoco il completamento prima dell'azione principale. Prima scegli la relazione, poi il tempo.")],
  ["future-in-past",ox("44","108-109","Un piano visto da un momento passato può usare was/were going to. Distingui il piano dall'effettiva realizzazione: la costruzione da sola non garantisce che il fatto sia avvenuto.")],
  ["used-to",ox("23, 82","62-63, 194-195","Used to + forma base: abitudine o stato passato. Be/get used to + nome o -ing: essere o diventare abituati. Would per abitudini passate richiede un contesto ed è inadatto a molti stati.")],
  ["ability negatives",ox("54-55","132-135","I modali non prendono -s e reggono la forma base. Negative e domande usano direttamente il modale. Per capacità in altri tempi può servire be able to; distingui abilità e permesso.")],
  ["may-might deduction hedging",ox("59-60","142-145","May/might/could esprimono possibilità nel contesto; must indica una deduzione forte e can't una deduzione negativa. Per deduzioni passate usa modale + have + participio. Non convertire ogni sfumatura in una percentuale fissa.")],
  ["obligation negatives",ox("57-58, 62","138-141, 148-149","Mustn't indica un divieto, don't have to/needn't assenza di necessità. Have to usa do nelle domande e negative; must no. Should esprime normalmente consiglio: una differenza di significato non è solo una differenza di registro.")],
  ["questions negatives indirect-questions",ox("65-67, 70","156-161, 168-169","Domande ordinarie: ausiliare prima del soggetto. Le domande sul soggetto non richiedono normalmente do. Nelle domande indirette la subordinata mantiene soggetto + verbo. Negative non contratte: ausiliare + soggetto + not.")],
  ["some-any quantifiers nouns negatives",ox("106, 114-118","248-249, 264-273","Numerabilità e contesto determinano il quantificatore. Some è possibile nelle offerte e richieste; any compare spesso in negative e domande e può significare qualsiasi. No/none/nobody negano già. Neither si riferisce a nessuno di due.")],
  ["phrasal-basics",ox("136-138","308-313","Studia espressione, significato e costruzione insieme. Nei separabili il pronome oggetto va fra verbo e particella; nei verbi inseparabili segue l'espressione. Nei verbi in tre parti il complemento normalmente viene dopo l'ultima particella.")],
  ["phrasal-basics",mission("33-34","Il manuale propone apprendimento del significato e riuso nel contesto. Integra significato, posizione dell'oggetto e registro. Evita la generalizzazione che tutti i verbi multi-parola siano inadatti a un testo professionale.")],
  ["verb-patterns prepositions",ox("75-80","180-191","Memorizza il verbo con la costruzione. Stop doing interrompe l'attività; stop to do indica una pausa per fare altro. Dopo una preposizione il verbo normalmente è in -ing; to non è sempre segnale di infinito.")],
  ["conditionals-real conditionals-unreal wish",ox("101-104","236-243","Distingui possibilità reale e ipotesi irreale, e presente/futuro da passato. Il terzo tipo richiede if + past perfect e would have + participio nella principale. Applica le errata: le formulazioni difettose MISSION/TARGET non sono regole da insegnare.")],
  ["passive reporting-passive",ox("47-52","116-127","Il passivo usa be nel tempo opportuno + participio. Mantieni il tempo della frase e distingui chi compie l'azione da chi la riceve. Il passivo impersonale richiede attenzione al riferimento temporale; non usarlo solo per rendere il testo più lungo.")],
  ["reported indirect-questions",mission("16-19","Nella narrazione riferita chiarisci il riferimento temporale e le persone. Il backshift dipende dal contesto: informazioni ancora valide non richiedono sempre un arretramento meccanico. Domande riferite senza inversione nella subordinata.")],
  ["reported indirect-questions",ox("97-100","228-235","Say e tell non hanno la stessa costruzione: tell normalmente ha un destinatario. Usa if/whether nelle domande yes/no riferite. Applica le correzioni alle note italiane di p. 228, già registrate nell'app.")],
  ["relatives participles",ox("157-160","354-361","Usa le relative per identificare o aggiungere informazione. Non ripetere il soggetto già espresso dal pronome relativo. Le virgole segnalano informazione aggiuntiva e possono cambiare il significato.")],
  ["clauses linkers cohesion mixed",target("14-18","Scegli il collegamento logico prima del connettivo: contrasto, causa, conseguenza o condizione. Distingui congiunzioni e avverbi di collegamento. Applica le errata su however e punteggiatura; non unire due frasi indipendenti con una sola virgola.")],
  ["linkers cohesion mixed",ox("164-167","370-379","Connettivi con significato vicino possono reggere strutture diverse: although + proposizione, despite + nome/-ing. However collega due enunciati con punteggiatura adeguata. Una frase complessa deve rendere chiaro il rapporto fra le idee.")],
  ["inversion",ox("177","400-401","Nell'inversione dopo alcune espressioni negative l'ausiliare precede il soggetto. L'enfasi non giustifica strutture opache: prima controlla l'ordine ordinario e il significato.")]
];
export const WRITING_SOURCES = {
  email:[camp("99","94","Nelle comunicazioni tra uffici esplicita scopo, richiesta e azione attesa. Insegna frasi funzionali e acronimi solo quando il destinatario li comprende; non copiare i messaggi del manuale.")],
  report:[mission("72, 78","Organizza un rapporto con fatti verificabili, sequenza chiara e attribuzione delle dichiarazioni. Prima raccogli le idee, poi ordinale; mantieni distinti osservazione, dichiarazione e inferenza."),camp("33, 51","29, 47","Trasferisci testimonianze a un rapporto in terza persona e separa sfondo, evento e azioni successive. Usa esercizi originali con informazioni fittizie.")],
  argument:[mission("23","Definisci una tesi e una scaletta prima di scrivere. Ogni paragrafo deve sviluppare un punto pertinente alla consegna."),target("154-155","Chiarisci argomento, destinatario e finalità. Sostieni le idee con ragioni, considera obiezioni e usa una conclusione coerente. Le indicazioni di stile non diventano divieti assoluti validi per tutti i generi.")]
};
export function bookContext(lessonId,mode="EXERCISES",type="report"){
  const lesson=LESSONS.find(l=>l.id===lessonId);
  let notes=packs.filter(([ids])=>ids.split(" ").includes(lessonId)).map(([,note])=>note).slice(0,4);
  if(mode.startsWith("WRITING"))notes=WRITING_SOURCES[type]||WRITING_SOURCES.report;
  if(mode==="ARTICLE_FEEDBACK")notes=[target("14-18","Individua proposizioni e collegamenti per ricostruire il senso; non tradurre soltanto parole isolate. Spiega ambiguità e riferimenti e riusa il lessico sconosciuto in esempi originali.")];
  const tags=[lessonId,lesson?.tool,...(mode.startsWith("WRITING")?[type==="argument"?"B2":"A4"]:[])].filter(Boolean);
  const errata=ERRATA.filter(e=>e.tags.some(t=>tags.includes(t))).slice(0,5).map(e=>({book:e.book,pages:e.pages,correction_it:e.fix}));
  const further=notes.length?[]:BOOK_REFS.filter(r=>r.tools.includes(lesson?.tool)&&r.reliability!=="excluded").slice(0,2).map(r=>({book:r.book,units:r.unit,pages:r.pages,status:r.page_status,purpose_it:r.use_it}));
  return {notes,errata,further,policy_it:"Sintesi didattiche originali basate sui materiali forniti. Applica le errata; non inventare citazioni, pagine o letture integrali. Le indicazioni ulteriori sono rimandi, non estratti del libro."};
}
