import {QUESTIONS,AREAS,PHRASAL_TARGETS,newPlacement,orderedQuestions,orderedOptions,placementProfile} from "./placement.js";
import {LESSONS,VOCABULARY} from "./catalog.js";
import {scheduleReview} from "./learning.js";
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const names={skip:"Puoi saltare per ora",review:"Da riprendere",confirm:"Da confermare"};
export function createPlacementUI({view,load,edit,flush,toast}){
  const $=s=>view.querySelector(s);
  async function show(part){
    await flush();const state=await load(),p=state.placement;
    if(part==="results"&&p?.submitted_at){await result(p);return;}
    if(part==="run"&&p&&!p.submitted_at){await question(p);return;}
    view.innerHTML=`<a href="#/learn">← Studio</a><span class="eyebrow">Scegliere da dove partire</span><h2>Pre-test di ingresso</h2><p class="muted">45 domande originali, soprattutto su tempi verbali, negazioni e phrasal verbs. Bastano poche domande per controllare le basi: il percorso non parte automaticamente dai soggetti.</p><section class="panel"><h3>Come funziona</h3><p>Scelte e brevi completamenti, senza glossario o indizi. Puoi rispondere “Non so”. Segna se sei sicuro: una risposta indovinata va confermata. Le spiegazioni arrivano dopo la consegna completa.</p><p>Le risposte si salvano sul dispositivo: puoi interrompere e riprendere. Stima: 20–30 minuti. Non serve il collegamento AI.</p></section><section class="panel"><h3>Cosa contiene</h3><ul>${Object.entries(AREAS).map(([area,label])=>`<li>${esc(label)}: ${QUESTIONS.filter(q=>q.area===area).length}</li>`).join("")}</ul></section>${p?.submitted_at?'<a class="btn" href="#/placement/results">Apri il tuo risultato</a><details class="panel"><summary>Ripetere il test</summary><p>La banca è la stessa: dopo aver letto le soluzioni, il risultato può riflettere anche la memoria. Per verificare i progressi usa le verifiche con esercizi nuovi.</p><button class="ghost" id="placement-start">Ripeti il pre-test</button></details>':p?'<a class="btn" href="#/placement/run">Riprendi il pre-test</a>':'<button id="placement-start">Inizia le 45 domande</button>'}<p class="small muted">Oxford guida le strutture; CAMPAIGN, MISSION e TARGET i contesti e la scrittura. È una selezione didattica del percorso, non un voto ufficiale JFLT o un livello certificato.</p>`;
    $("#placement-start")?.addEventListener("click",async()=>{const button=$("#placement-start");button.disabled=true;try{await edit(s=>s.placement=newPlacement());location.hash="#/placement/run";}catch(e){toast(e.message);button.disabled=false;}});
  }
  async function question(p){
    const ordered=orderedQuestions(p.seed),item=ordered[p.position],answer=p.answers.find(a=>a.id===item.id),last=p.position===44;
    view.innerHTML=`<a href="#/learn">← Salva e torna allo Studio</a><span class="eyebrow">Domanda ${p.position+1} di 45</span><h2>Pre-test di ingresso</h2><progress class="placement-progress" value="${p.answers.length}" max="45" aria-label="Domande compilate">${p.answers.length}/45</progress><p class="small muted">${p.answers.length} risposte salvate · nessuna soluzione mostrata prima della consegna.</p><section class="panel placement-question"><p class="stem">${esc(item.stem)}</p>${item.options?`<fieldset class="placement-options"><legend>Scegli una risposta</legend>${orderedOptions(item,p.seed).map((option,i)=>`<label class="placement-option"><input type="radio" name="placement-answer" value="${esc(option)}" ${answer?.value===option?"checked":""}><span>${String.fromCharCode(65+i)}. ${esc(option)}</span></label>`).join("")}</fieldset>`:`<label for="placement-answer">Scrivi solo la parte richiesta</label><input id="placement-answer" lang="en" spellcheck="false" autocorrect="off" autocomplete="off" maxlength="350" value="${esc(answer?.value||"")}">`}<label for="placement-confidence">Quanto sei sicuro?</label><select id="placement-confidence"><option value="unsure" ${answer?.confidence!=="sure"?"selected":""}>Non del tutto: da confermare</option><option value="sure" ${answer?.confidence==="sure"?"selected":""}>Sono sicuro</option></select><label class="checkline"><input id="placement-unknown" type="checkbox" ${answer?.value===""?"checked":""}> Non so rispondere</label></section><div class="row">${p.position?'<button class="ghost" id="placement-back">Indietro</button>':""}<button id="placement-next">${last?"Rivedi prima della consegna":"Salva e continua"}</button></div><p class="small muted">Evita traduttori e aiuti: il risultato serve a scegliere il lavoro utile per te. Puoi tornare alle domande precedenti.</p>`;
    let pendingSave=Promise.resolve();
    const save=()=>{
      const value=$("#placement-unknown").checked?"":(item.options?$("input[name=placement-answer]:checked")?.value:$("#placement-answer").value);
      if(value===undefined||(!value.trim()&&!$("#placement-unknown").checked)){pendingSave=edit(s=>{if(s.placement?.seed===p.seed&&!s.placement.submitted_at)s.placement.answers=s.placement.answers.filter(a=>a.id!==item.id);});return pendingSave;}
      const confidence=value?$("#placement-confidence").value:"unsure";
      pendingSave=edit(s=>{if(s.placement?.submitted_at||s.placement?.seed!==p.seed)return;const a={id:item.id,value:value.trim(),confidence};const i=s.placement.answers.findIndex(x=>x.id===item.id);if(i<0)s.placement.answers.push(a);else s.placement.answers[i]=a;});return pendingSave;
    };
    // Salvataggio immediato: anche chi chiude la pagina conserva la risposta.
    view.querySelectorAll('input,select').forEach(el=>el.addEventListener("input",()=>{save().catch(e=>toast(e.message));}));
    $("#placement-next").onclick=async()=>{
      if(!$("#placement-unknown").checked&&!(item.options?$("input[name=placement-answer]:checked")?.value:$("#placement-answer").value.trim())){toast("Rispondi oppure seleziona Non so.");return;}
      $("#placement-next").disabled=true;await save();await edit(s=>{if(!last)s.placement.position++;});if(last)await submitPage();else await question((await load()).placement);
    };
    $("#placement-back")?.addEventListener("click",async()=>{await save();await edit(s=>s.placement.position--);await question((await load()).placement);});
  }
  async function submitPage(){
    const p=(await load()).placement,order=orderedQuestions(p.seed),complete=p.answers.length===45;
    view.innerHTML=`<a href="#/learn">← Studio</a><h2>Consegna il pre-test</h2><section class="panel"><p>${p.answers.length} / 45 domande compilate. ${p.answers.filter(a=>!a.value).length} risposte “Non so”. Le spiegazioni si apriranno tutte insieme.</p><button id="placement-submit" ${complete?"":"disabled"}>Consegna e crea il percorso</button></section><h3>Rivedi una risposta</h3><div class="placement-jump">${order.map((q,i)=>`<button class="ghost" data-placement-jump="${i}" aria-label="Rivedi domanda ${i+1}">${i+1}${p.answers.some(a=>a.id===q.id)?" ✓":""}</button>`).join("")}</div>`;
    view.querySelectorAll("[data-placement-jump]").forEach(b=>b.onclick=async()=>{await edit(s=>s.placement.position=+b.dataset.placementJump);await question((await load()).placement);});
    $("#placement-submit").onclick=async()=>{const b=$("#placement-submit");b.disabled=true;await edit(s=>{if(s.placement.answers.length!==45)throw new Error("Completa le 45 domande.");s.placement.submitted_at=new Date().toISOString();for(const {item} of placementProfile(s.placement).errors){const v=VOCABULARY.find(v=>v.expression===PHRASAL_TARGETS[item.id]);if(v&&!s.reviews.some(r=>r.id===v.id))s.reviews.push(scheduleReview({id:v.id,front:`${v.expression}: significato, costruzione e una frase tua`,back:`${v.meaning_it}\n${v.example}\n${item.why}`,source:"pre-test: phrasal verbs"},"again"));}});location.hash="#/placement/results";};
  }
  async function result(p){
    const profile=placementProfile(p),priority=profile.priorityIds.map(id=>LESSONS.find(l=>l.id===id)).filter(Boolean),skipped=LESSONS.filter(l=>profile.lessonStatus[l.id]==="skip");
    view.innerHTML=`<a href="#/learn">← Il tuo percorso</a><span class="eyebrow">Il punto di partenza</span><h2>Risultato del pre-test</h2><section class="panel hero"><h3>${profile.correct} / 45 risposte corrette</h3><p>${profile.errors.length} risposte da riprendere · ${profile.uncertain.length} corrette ma da confermare.</p><a class="btn" href="#/lesson/${priority[0]?.id||"mixed"}">${priority.length?"Parti dalla priorità":"Apri una verifica con esercizi nuovi"} →</a></section><div class="table-wrap"><table><caption>Risultati per area</caption><thead><tr><th>Area</th><th>Corrette</th><th>Lettura del risultato</th></tr></thead><tbody>${profile.areas.map(a=>`<tr><td>${esc(a.title)}</td><td>${a.correct}/${a.total}</td><td>${a.status==="skip"?"Buona base nel campione":names[a.status]}</td></tr>`).join("")}</tbody></table></div><section class="panel"><h3>Da dove cominciare</h3>${priority.length?`<ol>${priority.slice(0,8).map(l=>`<li><a href="#/lesson/${l.id}">${esc(l.title)}</a></li>`).join("")}</ol>`:"<p>Nel campione non sono emersi errori. Una verifica nuova confermerà scelta, forma e uso personale.</p>"}<p class="small muted">Le risposte sbagliate o “Non so” creano priorità specifiche. Gli esiti positivi con poca evidenza restano da confermare: una singola scelta corretta non prova padronanza.</p></section><details class="panel"><summary>Argomenti che puoi saltare per ora (${skipped.length})</summary>${skipped.length?`<ul>${skipped.map(l=>`<li><a href="#/lesson/${l.id}">${esc(l.title)}</a></li>`).join("")}</ul>`:"<p>Servono ancora brevi verifiche per confermare gli argomenti.</p>"}<p>Le lezioni restano accessibili. Se emergono nuovi errori, tornano nelle priorità. Gli argomenti non campionati restano da valutare.</p></details><h3>Capire gli errori</h3>${profile.errors.length?profile.errors.map(({item,answer})=>feedback(item,answer,false)).join(""):"<p>Nessun errore in questo campione.</p>"}<details class="panel"><summary>Rivedi le risposte corrette (${profile.correct})</summary>${profile.rows.filter(r=>r.correct).map(({item,answer})=>feedback(item,answer,true)).join("")}</details><p class="small muted">Le soglie sono criteri pratici dell'app, non scale validate. Il test controlla un campione di grammatica e lessico; la scrittura si verifica nel laboratorio. I risultati si aggiornano con gli esercizi successivi.</p><a class="btn ghost" href="#/placement">Gestisci il pre-test</a>`;
  }
  function feedback(item,answer,correct){return `<section class="panel ${correct?"ok":"warn"}"><p class="stem">${esc(item.stem)}</p><p>La tua risposta: <strong>${esc(answer.value||"Non so")}</strong>${correct&&answer.confidence!=="sure"?" · da confermare":""}</p><p lang="en">Risposta di riferimento: <strong>${esc(item.answer)}</strong></p><p>${esc(item.why)}</p><p class="small muted">${esc(item.ref)}</p><p>${item.lessons.map(id=>`<a class="tag" href="#/lesson/${id}">${esc(LESSONS.find(l=>l.id===id)?.title||id)}</a>`).join(" ")}</p></section>`;}
  return {show};
}
