import {LESSONS} from "./catalog.js";
// Esercizi originali; nessuna domanda copiata dal pretest o dai manuali.
const rows = {
sentence:[["Riordina: checked / the guard / the list","The guard checked the list"],["Completa il verbo: The guards ___ the lists daily. (check)","check"]],
nouns:[["Completa: We need two ___ of information. (piece)","pieces"],["Correggi: She gave me an advice.","She gave me some advice","She gave me a piece of advice"]],
articles:[["Completa: She is ___ experienced investigator.","an"],["Completa: We travelled by ___ train. Scrivi — se non serve un articolo.","—","-","nessun articolo"]],
pronouns:[["Completa: I asked Anna to send ___ the file. (a me)","me"],["Completa: This is their office. The office is ___.","theirs"]],
"some-any":[["Completa con some o any: There aren't ___ seats left.","any"],["Completa: Would you like ___ coffee? (offerta)","some"]],
quantifiers:[["Completa con much o many: How ___ luggage is there?","much"],["Completa con few o little: We have very ___ time.","little"]],
adjectives:[["Completa l'avverbio: Please speak ___. (clear)","clearly"],["Completa con good o well: She performed ___.","well"]],
comparison:[["Completa: This option is ___ than the previous one. (cheap)","cheaper"],["Completa: It is the ___ solution available. (reliable)","most reliable"]],
questions:[["Completa solo l'ausiliare: ___ you send the message last night?","Did"],["Trasforma in domanda: She works here.","Does she work here?"]],
prepositions:[["Completa: The meeting is ___ Tuesday.","on"],["Completa con since o for: He has lived here ___ 2020.","since"]],
"present-simple":[["Completa l'abitudine: My colleague ___ the cameras every Friday. (test)","tests"],["Rendi negativa: He drives to work.","He does not drive to work","He doesn't drive to work"]],
"present-continuous":[["Completa l'azione in corso: Listen! Someone ___ at the door. (knock)","is knocking"],["Rendi negativa: They are recording the interview.","They are not recording the interview","They aren't recording the interview"]],
"past-simple":[["Completa al passato: We ___ the message last night. (send)","sent"],["Correggi: They didn't knew the address.","They did not know the address","They didn't know the address"]],
"past-continuous":[["Completa lo sfondo: She ___ lunch when the call arrived. (prepare)","was preparing"],["Completa la domanda: ___ they ___ outside at noon yesterday? (wait; scrivi il gruppo completo)","Were they waiting"]],
present:[["Azione temporanea: This month, I ___ in a different office. (work)","am working"],["Abitudine: She ___ to work every Monday. (cycle)","cycles"]],
past:[["Attività in corso: We ___ when the lights went out. (eat)","were eating"],["Evento concluso: He ___ the door and left. (close)","closed"]],
"perfect-simple":[["Completa al past simple: I ___ my wallet last Thursday. (lose)","lost"],["Risultato attuale, usa il present perfect: Someone ___ the window; the room is cold now. (open)","has opened"]],
"perfect-continuous":[["Risultato numerabile: He ___ five applications so far. (process; present perfect simple)","has processed"],["Processo ancora in corso: He ___ applications all morning. (process; present perfect continuous)","has been processing"]],
"past-perfect":[["Evento anteriore: The train ___ before we got there. (depart; past perfect simple)","had departed"],["Durata anteriore: We ___ for forty minutes when it opened. (queue; past perfect continuous)","had been queuing","had been queueing"]],
future:[["Decisione immediata: 'I'm tired.' 'I ___ you home.' (drive; will)","will drive","'ll drive"],["Piano già deciso, going to: We ___ the system next week. (upgrade)","are going to upgrade"]],
"used-to":[["Abitudine passata: She ___ in a hospital, but now she works here. (use to / work)","used to work"],["Completa: He is used to ___ early. (get up)","getting up"]],
ability:[["Completa senza to: She can ___ the form. (translate)","translate"],["Completa al futuro: After training, they ___ to operate the device. (be able)","will be able"]],
"may-might":[["Completa la possibilità con might: The schedule ___ next week. (change)","might change"],["Correggi: He may to arrive later.","He may arrive later"]],
obligation:[["Esprimi assenza di obbligo: You ___ wear a tie; it is optional. (have to; negativo)","do not have to","don't have to"],["Esprimi un divieto con must: Visitors ___ touch the equipment.","must not","mustn't"]],
negatives:[["Completa la negativa: She ___ the instructions. (understand; presente abituale)","does not understand","doesn't understand"],["Correggi: We didn't received a reply.","We did not receive a reply","We didn't receive a reply"],["Completa: They ___ waiting anymore. (be; presente negativo)","are not","aren't"]],
"verb-patterns":[["Completa: He avoided ___ about the incident. (talk)","talking"],["Completa: She agreed ___ us. (help)","to help"]],
"phrasal-basics":[["Sostituisci the lights con them: Please switch off the lights.","Please switch them off"],["Sostituisci the request con it: We will look into the request.","We will look into it"]],
"present-perfect-simple":[["Completa: The technician ___ the radio, so it works now. (repair; present perfect)","has repaired"],["Completa la negativa: We ___ the answer yet. (receive; present perfect)","have not received","haven't received"]],
"present-perfect-continuous":[["Completa: She ___ on the case since dawn and is still busy. (work)","has been working"],["Correggi: They have waiting for an hour.","They have been waiting for an hour"]],
"past-perfect-simple":[["Completa: By the time I arrived, everyone ___. (leave)","had left"],["Completa la negativa anteriore: They ___ the warning before the test started. (see)","had not seen","hadn't seen"]],
"past-perfect-continuous":[["Completa: His eyes were tired because he ___ for hours. (read)","had been reading"],["Correggi: She had been work all night.","She had been working all night"]],
"future-will":[["Completa la promessa con will: I ___ you as soon as I know. (tell)","will tell","'ll tell"],["Correggi: We will to contact you.","We will contact you"]],
"future-going-to":[["Completa il piano: I ___ a new laptop this weekend. (buy; going to)","am going to buy"],["Completa l'evidenza: Look at those clouds! It ___. (rain; going to)","is going to rain"]],
"future-arrangements":[["Accordo fissato, continuous: We ___ the trainer on Wednesday. (meet)","are meeting"],["Orario ufficiale, simple: The workshop ___ at 14:00 tomorrow. (begin)","begins"]],
"future-perfect":[["Completamento entro un limite: By Friday, we ___ the checks. (complete; future perfect)","will have completed"],["Attività in corso: At this time tomorrow, I ___. (travel; future continuous)","will be travelling","will be traveling"]],
deduction:[["Deduzione forte sul passato: She ___ the message; she replied to it. (must / read)","must have read"],["Impossibilità presente: He ___ in Rome; I can see him here in Milan. (can / be; negativo)","cannot be","can't be"]],
"conditionals-real":[["Completa: If it rains tomorrow, we ___ indoors. (stay; will)","will stay"],["Correggi: If the temperature will fall, we will close the road.","If the temperature falls, we will close the road"]],
"conditionals-unreal":[["Completa l'ipotesi irreale presente: If I had more time, I ___ another course. (take)","would take"],["Completa l'ipotesi irreale passata: If they had asked, we ___ them. (help)","would have helped"]],
wish:[["Completa il rimpianto passato: I wish I ___ the number. (save)","had saved"],["Completa il desiderio presente irreale: I wish I ___ more time. (have)","had"]],
passive:[["Trasforma al passivo: They repaired the camera.","The camera was repaired","The camera was repaired by them"],["Completa il passivo modale: The form must ___ before noon. (sign)","be signed"]],
reported:[["Riporta dal punto di vista di ieri: She said, 'I am busy.' → She said that she ___ busy.","was"],["Completa: He told me ___ outside. (wait)","to wait"]],
"indirect-questions":[["Riordina: Could you tell me / where / the office / is","Could you tell me where the office is?"],["Correggi: Do you know when does the class start?","Do you know when the class starts?"]],
relatives:[["Completa il pronome relativo: The person ___ called is waiting outside.","who","that"],["Completa: This is the building ___ we met.","where"]],
clauses:[["Completa la subordinata futura: I will call you when I ___. (arrive)","arrive"],["Completa: We waited until the rain ___. (stop; evento passato)","stopped"]],
linkers:[["Completa con although o despite: ___ the noise, she continued working.","Despite"],["Completa con although o despite: ___ it was noisy, she continued working.","Although"]],
"future-continuous":[["Completa: At eight tomorrow, the team ___ the equipment. (test)","will be testing"],["Correggi: I will be work at noon.","I will be working at noon"]],
"future-perfect-simple":[["Completa: By the end of the day, she ___ all the files. (check)","will have checked"],["Correggi: They will have finish by Monday.","They will have finished by Monday"]],
"future-perfect-continuous":[["Completa: By August, he ___ here for three years. (work; future perfect continuous)","will have been working"],["Correggi: By noon, we will have been wait for two hours.","By noon, we will have been waiting for two hours"]],
"future-in-past":[["Piano visto dal passato: They ___ us, but the phone failed. (call; going to)","were going to call"],["Futuro nel passato: He said he ___ the next day. (return; would)","would return"]],
"reporting-passive":[["Completa: She is believed ___ abroad now. (be)","to be"],["Completa: He is believed ___ the country last week. (leave)","to have left"]],
participles:[["Completa: ___ the report, she sent it to the office. (finish; azione conclusa prima)","Having finished"],["Completa: The documents ___ yesterday are on the desk. (receive)","received"]],
inversion:[["Completa: Never ___ I seen such a queue.","have"],["Correggi: Only then I understood the problem.","Only then did I understand the problem"]],
clefts:[["Completa: It was Anna ___ found the error.","who","that"],["Completa: What we need ___ more time.","is"]],
nominalisation:[["Completa il nome: The ___ of the route took two hours. (inspect)","inspection"],["Completa il nome: Their ___ was unexpected. (refuse)","refusal"]],
hedging:[["Completa con may per una possibilità prudente: This change ___ improve response times.","may"],["Correggi la struttura: The evidence appears suggesting a link.","The evidence appears to suggest a link"]],
subjunctive:[["Completa la costruzione formale: They recommended that he ___ present. (be; subjunctive)","be"],["Completa: It is essential that she ___ informed. (be; subjunctive)","be"]],
cohesion:[["Scegli il connettivo di conseguenza (therefore/however): The road was blocked. ___, we used another route.","Therefore"],["Scegli il connettivo di contrasto (therefore/however): The plan was useful. ___, it was too expensive.","However"]],
argument:[["Completa il nesso concessivo: ___ training is expensive, it reduces mistakes. (Although/Therefore)","Although"],["Completa la conclusione logica: Costs are lower and performance is better. ___, this option is preferable. (Therefore/Although)","Therefore"]],
mixed:[["Correggi: If we had left earlier, we would arrived on time.","If we had left earlier, we would have arrived on time"],["Correggi: She asked me where did I work.","She asked me where I worked"]]
};
export function grammarItems(lessonId, variation=0) {
  const bank=rows[lessonId];
  if(!bank)throw new Error("Lezione non disponibile.");
  return bank.map((row,i)=>({id:lessonId+"-offline-"+i,kind:row[0].startsWith("Correggi")?"error_correction":"completion",skill:"form",stem:row[0],answer:row[1],accept:row.slice(1),options:[],why:"Soluzione: "+row[1]+". "+(LESSONS.find(l=>l.id===lessonId)?.pitfall||""),origin:"local"})).sort((a,b)=>variation%2?a.id.localeCompare(b.id):b.id.localeCompare(a.id));
}
export const COVERED_LESSONS=Object.keys(rows);
