import {LESSONS,STAGES,PHRASALS,TERMS,VOCABULARY,PATTERNS,SOURCES,TENSE_GROUPS,TENSE_COMPARISONS} from "./catalog.js";
import * as learn from "./learning.js";
import {askAI,appToken,setAppToken,forgetToken,workerUrl} from "./ai-client.js";
import {validateAgainst,wordCount,todayISO} from "./core.js";
import {icon} from "./ui.js";
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const skills={recognise:"Riconoscere",choose:"Scegliere nel contesto",form:"Formare",write:"Usare nello scritto"};
const stageNames=["Consiglio e idee","Lessico","Scaletta","Paragrafi","Revisione","Riscrittura","Confronto"];
const attrs='lang="en" spellcheck="false" autocorrect="off" autocomplete="off"';
const wordRanges={email:[80,120],report:[150,250],argument:[250,450]};
export function createStudio({view,getSettings,put,all,toast,legacyRequest}){
  const $=s=>view.querySelector(s),$$=s=>[...view.querySelectorAll(s)];
  let queue=Promise.resolve(),busy=false;const saves=new Map();
  async function load(){const s=await getSettings();return {...learn.freshLearning(),...(s.learning||{})};}
  async function edit(fn){const work=queue.then(async()=>{const s=await getSettings(),state={...learn.freshLearning(),...(s.learning||{})};const value=fn(state);s.learning=state;await put("settings",s);return value;});queue=work.catch(()=>{});return work;}
  function saveSoon(key,fn){const old=saves.get(key);if(old)clearTimeout(old.timer);const item={fn,timer:setTimeout(()=>{saves.delete(key);edit(fn).catch(e=>toast(e.message));},250)};saves.set(key,item);}
  async function flush(){for(const item of saves.values()){clearTimeout(item.timer);await edit(item.fn);}saves.clear();await queue;}
  const goto=path=>{location.hash=`#/${path}`;};
  async function refresh(){await render(location.hash.replace(/^#\/?/,""));}
  async function act(fn){if(busy)return;busy=true;const controls=$$("button");controls.forEach(b=>b.disabled=true);const note=document.createElement("p");note.className="panel small";note.setAttribute("role","status");note.textContent="Le risposte sono salvate. Il tutor sta lavorando…";view.prepend(note);try{await flush();await fn();}catch(e){toast(e.message);const box=document.createElement("div");box.className="panel err";box.setAttribute("role","alert");box.textContent=e.message;view.prepend(box);}finally{busy=false;note.remove();controls.filter(b=>b.isConnected).forEach(b=>b.disabled=false);}}
  async function call(mode,data){
    const s=await getSettings(),state=await load();
    // Un timeout conserva una richiesta riutilizzabile, senza eseguirla in background.
    const existing=state.pending.find(p=>p.mode===mode&&JSON.stringify(p.data)===JSON.stringify(data));
    const req=existing||{id:learn.newId("ai"),mode,data,created_at:new Date().toISOString()};
    if(!existing)await edit(l=>l.pending.push(req));
    const payload=await askAI(s.ai_endpoint,mode,data,{request_id:req.id,onWarning:toast});
    const checked=mode==="EXERCISES"?{...data,already_seen:state.sets.flatMap(s=>s.items.map(i=>i.stem))}:data;
    const errors=learn.validateLearningReply(mode,payload,checked,validateAgainst);if(errors.length)throw new Error(`Risposta scartata: ${errors.join(" ")}`);
    await edit(l=>{l.pending=l.pending.filter(p=>p.id!==req.id);});return payload;
  }
  async function addTerm(g,source="testo"){
    const state=await load(),found=[...VOCABULARY,...state.vocabulary].find(v=>learn.normal(v.expression)===learn.normal(g.term||g.expression));
    const id=found?.id||`new-${encodeURIComponent(learn.normal(g.term||g.expression)).replaceAll("%","").slice(0,100)}`;
    await edit(l=>{
      if(!found&&!l.vocabulary.some(v=>v.id===id))l.vocabulary.push({id,expression:g.term||g.expression,meaning_it:g.meaning_it,example:g.example_en||g.example||"",topic:"dal testo",register:g.register||"neutro",pattern:g.pattern||"",alternative:"",difficulty:"personalizzato"});
      l.known=l.known.filter(k=>k!==id);
      if(!l.reviews.some(r=>r.id===id))l.reviews.push(learn.scheduleReview({id,front:`${g.term||g.expression}: significato e una frase tua`,back:`${g.meaning_it}\n${g.context_it||g.pattern||""}\n${g.example_en||g.example||""}`,source},"again"));
    });toast("Termine salvato: tornerà nei ripassi e negli esercizi.");
  }
  async function dashboard(){
    const state=await load(),s=await getSettings(),lesson=learn.suggestedLesson(state,s.plan?.focus_tool),due=state.reviews.filter(r=>Date.parse(r.due)<=Date.now());
    const unfinished=state.writers.find(w=>w.stage<6);
    view.innerHTML=`<span class="eyebrow">Il tuo percorso</span><h2>Studio</h2><p class="muted page-intro">Dalle fondamenta alle frasi complesse. Un percorso di 20 minuti, adattato alle tue risposte.</p>
      <section class="panel hero"><span class="eyebrow">Prossima lezione consigliata</span><h3>${esc(lesson.title)}</h3><p>${esc(lesson.goal)}</p><a class="btn" href="#/lesson/${lesson.id}">Spiegazione ed esercizi <span aria-hidden="true">→</span></a></section>
      <div class="section-head"><h3>Metti in pratica</h3><span class="small muted">Scegli da dove proseguire</span></div>
      <div class="study-grid"><a class="panel tile" href="#/review"><span class="card-icon">${icon("review")}</span><strong>Ripasso</strong><span>${due.length} carte da rivedere</span><span class="tile-link">Richiama e ricorda →</span></a><a class="panel tile" href="#/lexicon"><span class="card-icon">${icon("lexicon")}</span><strong>Lessico</strong><span>${PHRASALS.length} verbi multi-parola · ${TERMS.length} termini</span><span class="tile-link">Trova le parole giuste →</span></a><a class="panel tile" href="#/guided/${unfinished?.id||"new"}"><span class="card-icon">${icon("writing")}</span><strong>Scrittura passo passo</strong><span>${unfinished?"Riprendi il tuo testo":"Consiglio, lessico, scaletta, paragrafi"}</span><span class="tile-link">${unfinished?"Continua":"Prepara un testo"} →</span></a><a class="panel tile" href="#/articles"><span class="card-icon">${icon("article")}</span><strong>Leggere e tradurre</strong><span>Comprendi un articolo e recupera i termini nuovi</span><span class="tile-link">Lavora su un articolo →</span></a></div>
      <section class="panel"><span class="eyebrow">Grammatica dei verbi</span><h3>Tempi verbali</h3><p>Presente, passato e futuro: una lezione per ogni forma, poi confronti per scegliere quale usare. Completamenti, negazioni, domande e frasi tue.</p><a class="btn" href="#/tenses">Apri i tempi verbali →</a></section>
      <div class="row"><a class="btn ghost" href="#/progress">Progressi</a><a class="btn ghost" href="#/week">Piano settimanale</a><a class="btn ghost" href="#/connect">Tutor automatico</a><a class="btn ghost" href="#/diag">Diagnostico iniziale</a></div>
      <div class="section-head"><h3>Il programma completo</h3><span class="small muted">${LESSONS.length} lezioni · ${STAGES.length} tappe</span></div>${STAGES.map((title,stage)=>`<details class="panel" ${stage===0?"open":""}><summary>${stage+1}. ${title}<span class="course-stage">${LESSONS.filter(l=>l.stage===stage).length} lezioni</span></summary><ul class="lesson-list">${LESSONS.filter(l=>l.stage===stage).map(l=>`<li><a href="#/lesson/${l.id}">${esc(l.title)}</a><span class="small muted">${esc(l.goal)}</span></li>`).join("")}</ul></details>`).join("")}
      <p class="small muted">I livelli e le soglie dell'app sono didattici, non equivalenze o voti ufficiali STANAG. Lezioni e lessico disponibili offline dopo il primo caricamento.</p>`;
  }
  async function tenseProgram(){
    const state=await load();
    const links=ids=>ids.map(id=>{const lesson=LESSONS.find(l=>l.id===id),count=state.sets.filter(s=>s.lesson_id===id).length;return `<li><a href="#/lesson/${id}">${esc(lesson.title)}</a><span class="small muted">${esc(lesson.goal)}${count?` · ${count} blocchi salvati`:""}</span></li>`;}).join("");
    view.innerHTML=`<a href="#/learn">← Studio</a><span class="eyebrow">Spiegazioni ed esercizi</span><h2>Tempi verbali</h2><p class="muted">Scegli la forma da studiare. Prima capisci quando serve e come si costruisce; poi genera esercizi nuovi e verifica la tua scelta nel contesto.</p><section class="panel"><h3>Come ti eserciti</h3><p>In ogni blocco: significato, completamento del verbo, correzione di un errore, trasformazione in negativa o domanda, cambio di contesto e produzione di frasi tue. Le soluzioni si aprono dopo la correzione.</p></section>${TENSE_GROUPS.map(group=>`<section class="panel tense-group"><h3>${group.title}</h3><ul class="lesson-list">${links(group.ids)}</ul></section>`).join("")}<section class="panel"><h3>Scegliere tra tempi diversi</h3><p>Metti a confronto routine e processo, evento concluso e risultato presente, sequenza passata e anteriorità. Poi passa al ripasso misto.</p><ul class="lesson-list">${links(TENSE_COMPARISONS)}</ul></section><p class="small muted">Le voci del futuro sono costruzioni per esprimere il tempo futuro. Tutte le lezioni restano accessibili: non serve completarle per forza in ordine.</p>`;
  }
  async function lessonPage(id){
    const lesson=LESSONS.find(l=>l.id===id);if(!lesson){goto("learn");return;}const state=await load();
    view.innerHTML=`<a href="#/${lesson.exercise_focus?"tenses":"learn"}">← ${lesson.exercise_focus?"Tempi verbali":"Programma"}</a><h2>${esc(lesson.title)}</h2><p class="muted">${STAGES[lesson.stage]} · ${esc(lesson.goal)}</p>
      <section class="panel"><h3>Quando e perché</h3><p>${esc(lesson.when)}</p></section>
      ${lesson.forms?'<section class="panel"><h3>Come si costruisce</h3><p>'+esc(lesson.forms)+'</p></section>':""}
      <section class="panel contrast"><h3>Confronta il significato</h3>${lesson.examples.map(e=>`<p lang="en">${esc(e)}</p>`).join("")}<p class="small">${esc(lesson.contrast)}</p></section>
      <section class="panel warn"><h3>Attenzione</h3><p>${esc(lesson.pitfall)}</p></section>
      <label for="context">Contesto degli esercizi</label><select id="context"><option value="law enforcement">Law enforcement e lavoro operativo</option><option value="general">Vita quotidiana, viaggi e comunicazioni</option><option value="mixed">Contesti misti</option></select>
      <section class="panel"><h3>Cosa metti in pratica</h3><p>Gli esercizi lavorano su ${esc(lesson.title)}: comprendi il significato, completa la struttura, correggi un errore, trasforma una frase, confronta due contesti e scrivi frasi tue.</p></section>
      <p class="small muted">Si ripetono i concetti, non le stesse frasi. Introduciamo ${learn.vocabularyLoad(state)} termini nuovi per blocco; puoi aprire il glossario nell'allenamento.</p>
      <div class="row"><button id="generate">Genera 6 esercizi nuovi</button><button class="ghost" id="test">Verifica senza aiuti (10)</button></div>
      ${state.sets.filter(s=>s.lesson_id===id).slice(-5).reverse().map(s=>`<p><a href="#/practice/${s.id}">${s.purpose==="check"?"Verifica":"Esercitazione"} del ${new Date(s.created_at).toLocaleDateString("it-IT")}</a></p>`).join("")}
      <details><summary>Fonti e approfondimenti</summary>${SOURCES.map(([name,url])=>`<p><a href="${url}" target="_blank" rel="noopener">${esc(name)}</a></p>`).join("")}<p class="small muted">Spiegazioni originali di sintesi: le pagine dei tuoi libri e le errata restano in <a href="#/books">Libri</a>.</p></details>`;
    const make=purpose=>act(async()=>{const latest=await load();const n_items=purpose==="check"?10:6;const data={lesson,purpose,n_items,exercise_plan:learn.exerciseBlueprint(n_items),context:$("#context").value,already_seen:latest.sets.flatMap(s=>s.items.map(i=>i.stem)).slice(-30),recent_errors:latest.attempts.filter(a=>a.verdict==="incorrect").slice(-6).map(a=>({lesson_id:a.lesson_id,answer:a.answer.slice(0,350),explanation_it:a.explanation_it.slice(0,350)})),writing_errors:latest.writers.filter(w=>w.feedback).slice(-2).flatMap(w=>w.feedback.errors.filter(e=>e.kind==="error").slice(0,3)),vocabulary:learn.vocabularyFor(latest).map(v=>({expression:v.expression,meaning_it:v.meaning_it,pattern:v.pattern,register:v.register})),vocabulary_limit:learn.vocabularyLoad(latest),known_terms:[...VOCABULARY,...latest.vocabulary].filter(v=>latest.known.includes(v.id)).map(v=>v.expression),session_seed:crypto.randomUUID()};const p=await call("EXERCISES",data);const set={id:learn.newId("set"),lesson_id:id,purpose,created_at:new Date().toISOString(),items:p.items};await edit(l=>l.sets.push(set));goto(`practice/${set.id}`);});
    $("#generate").onclick=()=>make("practice");$("#test").onclick=()=>make("check");
  }
  async function practice(id){
    const state=await load(),set=state.sets.find(s=>s.id===id);if(!set){goto("learn");return;}const lesson=LESSONS.find(l=>l.id===set.lesson_id),attempts=state.attempts.filter(a=>a.set_id===id),exam=set.purpose==="check",finished=attempts.filter(a=>a.submitted).length===set.items.length;
    const itemHtml=it=>{
      const a=attempts.find(x=>x.item_id===it.id),reveal=!exam||finished;
      const parts=learn.glossParts(it.stem,it.glosses);
      return `<section class="panel exercise-card" id="item-${esc(it.id)}"><div class="exercise-heading"><span class="eyebrow">Esercizio ${set.items.indexOf(it)+1} / ${set.items.length}</span><span class="tag">${skills[it.skill]}</span></div><p>${esc(it.instruction_it)}</p><p class="small muted">${esc(it.context_it)}</p><p class="stem" lang="en">${parts.map(p=>p.gloss&&!exam?`<button class="word-help" data-gloss="${esc(it.id)}" data-term="${esc(p.gloss.term)}">${esc(p.text)}</button>`:esc(p.text)).join("")}</p><div data-gloss-box="${esc(it.id)}"></div>
        <label for="answer-${esc(it.id)}">La tua risposta</label><textarea class="answer" id="answer-${esc(it.id)}" data-answer="${esc(it.id)}" ${attrs} ${exam&&finished?"readonly":""}>${esc(a?.answer||"")}</textarea>
        ${["choice","context_switch","production"].includes(it.kind)?`<label for="rationale-${esc(it.id)}">Perché hai scelto questa forma? (anche in italiano)</label><textarea class="answer" id="rationale-${esc(it.id)}" data-rationale="${esc(it.id)}" ${exam&&finished?"readonly":""}>${esc(a?.rationale||"")}</textarea>`:""}
        ${!exam?`<div class="row"><button class="ghost" data-hint="${esc(it.id)}">Aiuto ${(a?.hint_level||0)+1>3?"già completo":(a?.hint_level||0)+1}</button><button class="ghost" data-card="${esc(it.id)}">Salva per il ripasso</button></div>${a?.hint_level?`<p class="panel warn small">${esc(it.hints[a.hint_level-1])}</p>`:""}`:""}
        ${a?.submitted&&reveal?`<div class="panel ${a.verdict==="uncertain"?"warn":["correct","acceptable"].includes(a.verdict)?"ok":"err"}"><strong>${{correct:"Corretto",acceptable:"Variante accettabile",incorrect:"Da rivedere",uncertain:"Da valutare nel contesto"}[a.verdict]}</strong><p class="small prewrap">${esc(a.explanation_it)}</p>${a.verdict!=="uncertain"?`<details><summary>Soluzione di riferimento e spiegazione</summary><p lang="en">${esc(it.answer)}</p><p>${esc(it.reason_it)}</p></details>`:""}</div>`:""}</section>`;
    };
    view.innerHTML=`<a href="#/lesson/${lesson.id}">← ${esc(lesson.title)}</a><h2>${exam?"Verifica senza aiuti":"Esercitazione"}</h2><p class="muted">Le risposte si salvano automaticamente. ${exam?"Niente glossario, indizi o correzioni prima della consegna completa.":"Le parole sottolineate aprono significato e contesto. Gli aiuti vengono registrati: non contano come prova autonoma."}</p>${set.items.map(itemHtml).join("")}${exam&&finished?`<p class="panel ok">Verifica consegnata. Le risposte restano ferme: per una nuova prova genera esercizi diversi. Gli esiti dubbi non contano nei progressi.</p><a class="btn" href="#/lesson/${lesson.id}">Nuova verifica</a>`:`<button class="full" id="evaluate">${finished?"Ricorreggi le risposte modificate":"Correggi le risposte con il tutor"}</button>`}<p class="small muted">L'AI può sbagliare: le risposte ambigue restano da chiarire, non diventano automaticamente errori.</p>`;
    function update(it,key,value,extra={}){return edit(l=>{let a=l.attempts.find(x=>x.set_id===id&&x.item_id===it.id);if(!a){a={id:learn.newId("answer"),set_id:id,item_id:it.id,lesson_id:set.lesson_id,answer:"",rationale:"",skill:it.skill,assisted:false,submitted:false,hint_level:0,verdict:"uncertain",date:new Date().toISOString(),explanation_it:""};l.attempts.push(a);}a[key]=value;Object.assign(a,extra);});}
    $$("[data-answer],[data-rationale]").forEach(el=>el.oninput=()=>{if(exam&&finished)return;const itemId=el.dataset.answer||el.dataset.rationale,it=set.items.find(i=>i.id===itemId),key=el.dataset.answer?"answer":"rationale",value=el.value;saveSoon(`${id}:${itemId}:${key}`,l=>{let a=l.attempts.find(x=>x.set_id===id&&x.item_id===itemId);if(!a){a={id:learn.newId("answer"),set_id:id,item_id:itemId,lesson_id:set.lesson_id,answer:"",rationale:"",skill:it.skill,assisted:false,submitted:false,hint_level:0,verdict:"uncertain",date:new Date().toISOString(),explanation_it:""};l.attempts.push(a);}if(a.submitted)a.assisted=true;a[key]=value;a.submitted=false;a.verdict="uncertain";});});
    $$("[data-hint]").forEach(b=>b.onclick=async()=>{await flush();const it=set.items.find(i=>i.id===b.dataset.hint),current=(await load()).attempts.find(a=>a.set_id===id&&a.item_id===it.id);await update(it,"hint_level",Math.min(3,(current?.hint_level||0)+1),{assisted:true});await refresh();});
    $$("[data-gloss]").forEach(b=>b.onclick=async()=>{await flush();const it=set.items.find(i=>i.id===b.dataset.gloss),g=it.glosses.find(g=>g.term===b.dataset.term);await update(it,"assisted",true);const box=$$('[data-gloss-box]').find(el=>el.dataset.glossBox===it.id);box.innerHTML=`<aside class="panel word-definition" role="note"><strong>${esc(g.term)} — ${esc(g.meaning_it)}</strong><p>${esc(g.context_it)}</p><p lang="en">${esc(g.example_en)}</p><div class="row"><button class="ghost" data-learn-word>Non lo conoscevo</button><button class="ghost" data-know-word>Lo conosco</button><button class="ghost" data-close-word>Chiudi</button></div></aside>`;box.querySelector("[data-learn-word]").onclick=()=>addTerm(g,"esercizio");box.querySelector("[data-close-word]").onclick=()=>box.replaceChildren();box.querySelector("[data-know-word]").onclick=async()=>{await addTerm(g);const l=await load(),v=[...VOCABULARY,...l.vocabulary].find(v=>learn.normal(v.expression)===learn.normal(g.term));await edit(s=>{if(v&&!s.known.includes(v.id))s.known.push(v.id);s.reviews=s.reviews.filter(r=>r.id!==v?.id);});toast("Registrato come conosciuto.");};});
    $$("[data-card]").forEach(b=>b.onclick=()=>act(async()=>{const it=set.items.find(i=>i.id===b.dataset.card);await edit(l=>{const cid=`${id}:${it.id}`;if(!l.reviews.some(r=>r.id===cid))l.reviews.push(learn.scheduleReview({id:cid,front:`${it.instruction_it}\n${it.stem}`,back:`${it.answer}\n${it.reason_it}`,source:lesson.title},"again"));});toast("Esercizio aggiunto al ripasso.");}));
    $("#evaluate")?.addEventListener("click",()=>act(async()=>{
      const latest=await load(),aa=latest.attempts.filter(a=>a.set_id===id&&a.answer.trim());if(exam&&aa.length!==set.items.length)throw new Error("Completa tutte le risposte prima della consegna della verifica.");if(!aa.length)throw new Error("Scrivi almeno una risposta.");
      const data={lesson,items:set.items.filter(i=>aa.some(a=>a.item_id===i.id)),answers:aa.map(a=>({item_id:a.item_id,user_answer:a.answer,rationale:a.rationale})),purpose:set.purpose};
      const p=await call("EVALUATE",data);await edit(l=>{for(const r of p.results){const a=l.attempts.find(a=>a.set_id===id&&a.item_id===r.item_id);a.verdict=r.verdict;a.explanation_it=[r.explanation_it,r.fix?`${r.issue==="style"?"Alternativa di stile":"Correzione minima"}: ${r.fix}`:""].filter(Boolean).join("\n");a.submitted=true;a.date=new Date().toISOString();}});await refresh();
      if(p.results.filter(r=>r.verdict==="incorrect").length>=3)toast("Tre o più difficoltà: torna alla spiegazione prima di un nuovo blocco.");
    }));
  }
  async function lexiconPage(id){
    const state=await load(),lex=[...VOCABULARY,...state.vocabulary];
    if(id){const v=lex.find(v=>v.id===id);if(!v){goto("lexicon");return;}view.innerHTML=`<a href="#/lexicon">← Raccolta</a><h2 lang="en">${esc(v.expression)}</h2><section class="panel"><p>${esc(v.meaning_it)}</p>${v.pattern?`<p class="small">${esc(PATTERNS[v.pattern]||v.pattern)}</p>`:""}<p class="stem" lang="en">${esc(v.example)}</p><p class="small">Registro: ${esc(v.register)} · contesto: ${esc(v.topic)}${v.alternative?` · alternativa: <span lang="en">${esc(v.alternative)}</span>`:""}</p></section><div class="row"><button id="keep">Da imparare / ripassare</button><button class="ghost" id="known">Lo conosco</button><a class="btn ghost" href="#/lesson/phrasal-basics">Esercizi nuovi</a></div><p class="small muted">Un significato selezionato per voce: altri significati possono avere costruzioni diverse. Il registro dipende anche dal contesto. I livelli sono organizzativi, non etichette CEFR verificate.</p>${v.dictionary_url?`<a href="${v.dictionary_url}" target="_blank" rel="noopener">Consulta il dizionario</a>`:""}`;$("#keep").onclick=()=>addTerm(v,"lessico");$("#known").onclick=async()=>{await edit(l=>{if(!l.known.includes(id))l.known.push(id);l.reviews=l.reviews.filter(r=>r.id!==id);});toast("Registrato come conosciuto.");};return;}
    view.innerHTML=`<h2>Phrasal verbs e lessico</h2><p class="muted">${PHRASALS.length} verbi multi-parola, ${TERMS.length} termini selezionati e ${state.vocabulary.length} parole dai tuoi testi. Raccolta ampia, non dizionario esaustivo: include anche verbi preposizionali e phrasal-prepositional.</p><label for="search">Cerca in inglese o italiano</label><input type="text" id="search" placeholder="carry out, indagare, custody…"><div class="study-grid"><div><label for="group">Gruppo</label><select id="group"><option value="">Tutti</option><option value="pv">Phrasal / multi-word verbs</option><option value="lex">Termini e collocazioni</option><option value="new">Dai tuoi testi</option></select></div><div><label for="topic">Contesto</label><select id="topic"><option value="">Tutti</option>${[...new Set(lex.map(v=>v.topic))].map(t=>`<option>${esc(t)}</option>`).join("")}</select></div></div><label class="checkline"><input type="checkbox" id="unknown"> Solo quelli non segnati come conosciuti</label><div id="lex-results"></div><p class="small muted">Le definizioni sono di orientamento linguistico. Per termini giuridici verifica il significato nel sistema di riferimento: non sono consulenza legale.</p>`;
    let limit=30;
    function draw(){const q=learn.normal($("#search").value),group=$("#group").value,topic=$("#topic").value;const found=lex.filter(v=>(!q||learn.normal(`${v.expression} ${v.meaning_it}`).includes(q))&&(!group||v.id.startsWith(group))&&(!topic||v.topic===topic)&&(!$("#unknown").checked||!state.known.includes(v.id)));$("#lex-results").innerHTML=`<p class="small muted">${found.length} voci</p><ul class="lesson-list">${found.slice(0,limit).map(v=>`<li><a href="#/lexicon/${v.id}" lang="en">${esc(v.expression)}</a><span>${esc(v.meaning_it)}</span><span class="small muted">${esc(v.topic)} · ${esc(v.register)}${state.known.includes(v.id)?" · conosciuto":""}</span></li>`).join("")}</ul>${found.length>limit?'<button class="ghost" id="more-words">Mostra altre 30 voci</button>':""}`;$("#more-words")?.addEventListener("click",()=>{limit+=30;draw();});}
    ["#search","#group","#topic","#unknown"].forEach(sel=>$(sel).addEventListener(sel==="#search"?"input":"change",()=>{limit=30;draw();}));draw();
  }
  async function review(){
    // Migra le carte scelte nell'app precedente, senza modificarne l'archivio originale.
    const old=await all("cards");await edit(l=>{for(const c of old){const id=`old-${c.id}`;if(!l.reviews.some(r=>r.id===id))l.reviews.push(learn.scheduleReview({id,front:c.front,back:c.back,source:"errori precedenti"},"again",Date.now()-600001));}});
    const state=await load(),due=state.reviews.filter(r=>Date.parse(r.due)<=Date.now()).sort((a,b)=>a.due.localeCompare(b.due)),card=due[0];
    if(!card){view.innerHTML=`<h2>Ripasso</h2><section class="panel ok"><p>Nessuna carta in scadenza. ${state.reviews.length} carte salvate.</p></section><a class="btn" href="#/learn">Torna allo Studio</a>`;return;}
    view.innerHTML=`<h2>Ripasso · ${due.length} in scadenza</h2><p class="small muted">Prima prova a ricordare e, per il lessico, inventa una frase. L'autovalutazione non è una prova di acquisizione.</p><section class="panel"><p class="stem" lang="en">${esc(card.front)}</p><button class="ghost" id="reveal">Mostra spiegazione</button><div id="back" hidden><p class="prewrap">${esc(card.back)}</p><div class="row">${[["again","Non ricordo"],["hard","Con fatica"],["good","Ricordo"],["easy","Facile"]].map(([v,t])=>`<button class="ghost" data-grade="${v}">${t}</button>`).join("")}</div></section><p class="small muted">${esc(card.source)} · intervalli adattivi dell'app, non una garanzia di memorizzazione.</p>`;$("#reveal").onclick=()=>{$("#back").hidden=false;$("#reveal").hidden=true;};$$("[data-grade]").forEach(b=>b.onclick=async()=>{await edit(l=>{const i=l.reviews.findIndex(c=>c.id===card.id);l.reviews[i]=learn.scheduleReview(l.reviews[i],b.dataset.grade);});await refresh();});
  }
  async function writerPage(id){
    if(!id||id==="new"){
      const state=await load();view.innerHTML=`<h2>Scrittura passo passo</h2><p class="muted">Prima consiglio, poi termini e costruzioni, scaletta e paragrafi. Sei tu a scrivere. Il modello arriva dopo la riscrittura.</p><label for="type">Tipo di testo</label><select id="type"><option value="email">Email</option><option value="report">Rapporto</option><option value="argument">Testo argomentativo</option></select><label for="topic">Argomento o consegna (anche in italiano)</label><textarea class="answer" id="topic" placeholder="Es. rapporto su un controllo, richiesta di informazioni, confronto tra due procedure…"></textarea><label for="mode">Modalità</label><select id="mode"><option value="guided">Allenamento guidato</option><option value="exam">Simulazione autonoma, senza aiuti</option></select><button class="full" id="start-writing">Prepara il tuo testo</button><p class="small" style="margin-top:16px"><a href="#/write">Apri l’archivio degli scritti precedenti</a></p>${state.writers.length?`<h3>I tuoi lavori</h3><ul class="lesson-list">${state.writers.slice().reverse().map(w=>`<li><a href="#/guided/${w.id}">${esc(w.topic)}</a><span class="small muted">${w.mode==="exam"?"Simulazione":"Guidato"} · ${stageNames[w.stage]}</span></li>`).join("")}</ul>`:""}`;
      $("#start-writing").onclick=()=>act(async()=>{const topic=$("#topic").value.trim();if(topic.length<8)throw new Error("Scrivi un argomento o una consegna un po' più precisa.");const type=$("#type").value,mode=$("#mode").value,w={id:learn.newId("write"),type,mode,topic,prompt:`${type}: ${topic}`,stage:mode==="exam"?3:0,ideas:"",outline:"",paragraphs:["","","",""],rewrite:"",coaching:{advice:null,vocabulary:null,outline:null,paragraph:null},feedback:null,model:null,created_at:new Date().toISOString()};await edit(l=>l.writers.push(w));goto(`guided/${w.id}`);});return;
    }
    const state=await load(),w=state.writers.find(w=>w.id===id);if(!w){goto("guided/new");return;}const range=wordRanges[w.type],draft=w.paragraphs.filter(p=>p.trim()).join("\n\n"),guided=w.mode==="guided";
    const tip={email:"Indica subito perché scrivi, poi la richiesta e le informazioni necessarie. Chiudi con il passo che attendi dal destinatario.",report:"Separa fatti osservati, fonti, sequenza temporale e azioni svolte. Non presentare un sospetto come un fatto.",argument:"Formula una tesi, sostienila con ragioni, considera un'obiezione e concludi con una raccomandazione motivata."}[w.type];
    let body="";
    if(w.stage===0)body=`<section class="panel"><p>${esc(w.coaching.advice?.advice_it||tip)}</p>${w.coaching.advice?.questions.map(q=>`<p>${esc(q)}</p>`).join("")||""}</section><label for="ideas">Che cosa vuoi comunicare? Quali fatti o idee hai?</label><textarea class="answer" id="ideas">${esc(w.ideas)}</textarea><button class="ghost" id="coach" data-stage="advice">Consiglio personalizzato</button><button id="next">Passa al lessico</button>`;
    if(w.stage===1){const terms=w.coaching.vocabulary?.terms||learn.vocabularyFor(state,w.type==="report"?"indagini":w.type==="argument"?"argomentazione":"relazioni",4).map(v=>({expression:v.expression,meaning_it:v.meaning_it,pattern:PATTERNS[v.pattern]||v.pattern,example_en:v.example,register:v.register}));body=`<p>Studia pochi termini utili prima di scrivere: significato, costruzione e registro. Non sono parole da inserire tutte obbligatoriamente.</p>${terms.map((t,i)=>`<section class="panel"><h3 lang="en">${esc(t.expression)}</h3><p>${esc(t.meaning_it)}</p><p class="small">${esc(t.pattern)}</p><p lang="en">${esc(t.example_en)}</p><span class="tag">${esc(t.register)}</span><button class="ghost" data-term-keep="${i}">Non lo conoscevo</button></section>`).join("")}<button class="ghost" id="coach" data-stage="vocabulary">Lessico personalizzato per la consegna</button><button id="next">Prepara la scaletta</button>`;}
    if(w.stage===2)body=`${w.coaching.outline?`<section class="panel"><p>${esc(w.coaching.outline.advice_it)}</p><ol>${w.coaching.outline.outline.map(o=>`<li>${esc(o)}</li>`).join("")}</ol></section>`:`<p>Scrivi un punto per paragrafo: apertura, sviluppo, eventuale confronto/obiezione, conclusione.</p>`}<label for="outline">La tua scaletta</label><textarea class="answer" id="outline">${esc(w.outline)}</textarea><button class="ghost" id="coach" data-stage="outline">Aiuto sulla struttura</button><button id="next">Scrivi il primo paragrafo</button>`;
    if(w.stage===3)body=`<p>${guided?"Scrivi un paragrafo alla volta. Il tutor corregge solo il passaggio che gli sottoponi, senza sostituirlo con un testo completo.":"Simulazione senza suggerimenti: nessun lessico, glossario o feedback durante la stesura."}</p>${range[1]>250?`<div class="panel warn"><p>Testo lungo: due blocchi di stesura, proposti su due settimane. Prima sviluppa i paragrafi 1–2; poi completa 3–4. Le bozze restano nello stesso lavoro.</p></div>`:""}${guided&&w.outline?`<details><summary>La tua scaletta</summary><p class="prewrap">${esc(w.outline)}</p></details>`:""}${w.paragraphs.map((p,i)=>`<section class="panel"><label for="paragraph-${i}">Paragrafo ${i+1}</label><textarea class="answer" id="paragraph-${i}" data-paragraph="${i}" ${attrs}>${esc(p)}</textarea>${guided?`<button class="ghost" data-paragraph-feedback="${i}">Consiglio su questo paragrafo</button>`:""}</section>`).join("")}<div id="paragraph-feedback">${w.coaching.paragraph?coachHtml(w.coaching.paragraph):""}</div><p class="small">${wordCount(draft)} parole · intervallo di allenamento ${range[0]}–${range[1]} (non requisito ufficiale verificato)</p><button id="review-writing">Consegna e chiedi la revisione</button>`;
    if(w.stage>=4){body=`<h3>Il tuo testo</h3><div class="panel prewrap" lang="en">${esc(draft)}</div>${w.feedback?`<h3>Priorità</h3><ol>${w.feedback.priorities.map(p=>`<li>${esc(p)}</li>`).join("")}</ol><section class="panel">${Object.entries(w.feedback.rubric).map(([k,v])=>`<p>${esc(k)}: ${esc(v)}</p>`).join("")}</section>${correctionsHtml(w.feedback.errors,true)}<p>${esc(w.feedback.rewrite_it)}</p><p class="small muted">${esc(w.feedback.note)}</p>`:""}<label for="rewrite">Riscrivi con le tue parole</label><textarea class="sheet" id="rewrite" ${attrs}>${esc(w.rewrite)}</textarea><button id="model">Salva la riscrittura e confronta il modello</button>${w.model?`<h3>Modello di confronto</h3><div class="panel model" lang="en">${esc(w.model.model_en)}</div><ul>${w.model.comparison_it.map(x=>`<li>${esc(x)}</li>`).join("")}</ul><p>${w.model.remaining_it.map(esc).join(" · ")}</p>`:""}`;}
    const track=guided?[0,1,2,3,4,5,6]:[3,4,5,6];
    view.innerHTML=`<a href="#/guided/new">← I tuoi scritti</a><div class="section-head"><span class="eyebrow">${guided?"Scrittura guidata":"Simulazione autonoma"}</span><span class="tag">${{email:"Email",report:"Rapporto",argument:"Argomentazione"}[w.type]}</span></div><ol class="writing-track" aria-label="Passaggi della scrittura">${track.map((stage,i)=>`<li class="${stage<w.stage?"is-done":""}" ${stage===w.stage?'aria-current="step"':""}><span class="track-dot" aria-hidden="true">${stage<w.stage?"✓":i+1}</span><span>${stageNames[stage]}</span>${stage===w.stage?'<span class="sr-only">Passaggio attuale</span>':""}</li>`).join("")}</ol><h2>${stageNames[w.stage]}</h2><section class="panel writing-brief"><span class="eyebrow">La tua consegna</span><p>${esc(w.topic)}</p><p class="small muted">${guided?"Allenamento guidato, non prova autonoma":"Simulazione autonoma"} · Salvataggio automatico</p></section>${body}`;
    const activeStep=$(".writing-track [aria-current=step]"),trackElement=$(".writing-track");if(activeStep)trackElement.scrollLeft=Math.max(0,activeStep.offsetLeft-(trackElement.clientWidth-activeStep.clientWidth)/2);
    const bindText=(sel,key)=>$(sel)?.addEventListener("input",e=>{const value=e.target.value;saveSoon(`${id}:${key}`,l=>{l.writers.find(w=>w.id===id)[key]=value;});});bindText("#ideas","ideas");bindText("#outline","outline");bindText("#rewrite","rewrite");
    $$("[data-paragraph]").forEach(el=>el.oninput=()=>{const value=el.value,i=+el.dataset.paragraph;saveSoon(`${id}:paragraph:${i}`,l=>{l.writers.find(w=>w.id===id).paragraphs[i]=value;});});
    $("#next")?.addEventListener("click",()=>act(async()=>{await edit(l=>{const w=l.writers.find(w=>w.id===id);if(w.stage===0&&!w.ideas.trim())throw new Error("Annota prima le tue idee.");if(w.stage===2&&!w.outline.trim())throw new Error("Prepara prima una breve scaletta.");w.stage++;});await refresh();}));
    async function coach(stage,paragraph=""){
      const latest=await load(),current=latest.writers.find(w=>w.id===id);if(current.mode!=="guided")throw new Error("Aiuti disattivati nella simulazione.");
      const p=await call("WRITING_COACH",{stage,mode:current.mode,task:current.prompt,ideas:current.ideas,outline:current.outline,paragraph,vocabulary:learn.vocabularyFor(latest).map(v=>({expression:v.expression,meaning_it:v.meaning_it,pattern:PATTERNS[v.pattern]||v.pattern,register:v.register})),known_terms:[...VOCABULARY,...latest.vocabulary].filter(v=>latest.known.includes(v.id)).map(v=>v.expression)});await edit(l=>l.writers.find(w=>w.id===id).coaching[stage]=p);await refresh();
    }
    $("#coach")?.addEventListener("click",()=>act(()=>coach($("#coach").dataset.stage)));
    $$("[data-term-keep]").forEach(b=>b.onclick=()=>act(async()=>{const terms=w.coaching.vocabulary?.terms||learn.vocabularyFor(state,w.type==="report"?"indagini":w.type==="argument"?"argomentazione":"relazioni",4).map(v=>({...v,example_en:v.example}));await addTerm(terms[+b.dataset.termKeep],"scrittura");}));
    $$("[data-paragraph-feedback]").forEach(b=>b.onclick=()=>act(async()=>{const latest=await load(),p=latest.writers.find(w=>w.id===id).paragraphs[+b.dataset.paragraphFeedback];if(!p.trim())throw new Error("Scrivi prima il paragrafo.");await coach("paragraph",p);}));
    $("#review-writing")?.addEventListener("click",()=>act(async()=>{const current=(await load()).writers.find(w=>w.id===id),text=current.paragraphs.filter(p=>p.trim()).join("\n\n");if(wordCount(text)<30)throw new Error("Scrivi almeno 30 parole prima della revisione.");const p=await call("WRITING_REVIEW",{task:current.prompt,text,mode:current.mode,used_guidance:current.mode==="guided"});await edit(l=>{const w=l.writers.find(w=>w.id===id);w.feedback=p;w.stage=5;});await refresh();}));
    $("#model")?.addEventListener("click",()=>act(async()=>{const current=(await load()).writers.find(w=>w.id===id);if(!current.rewrite.trim())throw new Error("Il modello si sblocca dopo la tua riscrittura.");const p=await call("WRITING_MODEL",{task:current.prompt,text:draft,rewrite:current.rewrite,feedback:current.feedback});await edit(l=>{const w=l.writers.find(w=>w.id===id);w.model=p;w.stage=6;});await refresh();}));
    $$("[data-error-review]").forEach(b=>b.onclick=()=>act(async()=>{const e=w.feedback.errors[+b.dataset.errorReview],cid=`${id}:error:${b.dataset.errorReview}`;await edit(l=>{if(!l.reviews.some(r=>r.id===cid))l.reviews.push(learn.scheduleReview({id:cid,front:`Correggi e spiega: ${e.quote}`,back:`${e.fix}\n${e.reason_it}`,source:"errore dello scritto"},"again"));});toast("Errore salvato nel ripasso.");}));
  }
  function correctionsHtml(errors,review=false){return errors.map((e,i)=>`<section class="fix ${e.kind==="style"?"alt":""}"><span class="tag">${e.kind==="style"?"Alternativa stilistica":"Errore"}</span><p class="was" lang="en">${esc(e.quote)}</p><p class="now" lang="en">${esc(e.fix)}</p><p class="why">${esc(e.reason_it)}</p>${review&&e.kind==="error"?`<button class="ghost" data-error-review="${i}">Salva l'errore per il ripasso</button>`:""}</section>`).join("");}
  function coachHtml(p){return `<section class="panel"><p>${esc(p.advice_it)}</p>${correctionsHtml(p.feedback)}<p>${esc(p.next_action_it)}</p></section>`;}
  async function articlesPage(id){
    const state=await load();if(!id){view.innerHTML=`<h2>Leggere e tradurre</h2><p class="muted">Leggi prima l'inglese, prova a tradurlo senza aiuti e poi confronta significato e contesto. I termini che scegli torneranno negli esercizi.</p><label>Link alla fonte (facoltativo)</label><input type="text" id="article-url" placeholder="https://…"><button class="ghost" id="from-link">Carica un breve estratto pubblico</button><p class="small muted">BBC, Guardian, Reuters, AP, NPR e DW: solo estratti brevi, nessun paywall aggirato. Per un articolo o passaggio più lungo, incolla il testo che vuoi studiare.</p><label>Testo inglese (massimo 12.000 caratteri)</label><textarea class="sheet" id="article-text" maxlength="12000" lang="en"></textarea><button id="start-article">Leggi e prova la tua traduzione</button>${state.articles.length?`<h3>I tuoi testi</h3><ul class="lesson-list">${state.articles.slice().reverse().map(a=>`<li><a href="#/articles/${a.id}">${esc(a.text.slice(0,85))}…</a></li>`).join("")}</ul>`:""}`;
      let sourceKind="pasted";$("#article-text").oninput=()=>{sourceKind="pasted";};
      $("#from-link").onclick=()=>act(async()=>{const s=await getSettings();if(!s.ai_endpoint||!appToken())throw new Error("Collega il Worker per importare un estratto, oppure incolla direttamente il testo.");const res=await fetch(`${workerUrl(s.ai_endpoint)}/article`,{method:"POST",credentials:"omit",headers:{"Content-Type":"application/json",Authorization:`Bearer ${appToken()}`},body:JSON.stringify({url:$("#article-url").value.trim()})});const p=await res.json();if(!res.ok)throw new Error(p.message);$("#article-text").value=p.text;$("#article-url").value=p.source_url;sourceKind="link_excerpt";toast(p.notice);});
      $("#start-article").onclick=()=>act(async()=>{const text=$("#article-text").value.trim(),source_url=$("#article-url").value.trim();if(wordCount(text)<5)throw new Error("Inserisci un passaggio inglese.");if(source_url){const u=new URL(source_url);if(u.protocol!=="https:"||u.username||u.password)throw new Error("La fonte deve usare HTTPS.");}const a={id:learn.newId("article"),source_url,source_kind:sourceKind,text,translation:"",feedback:null,created_at:new Date().toISOString()};await edit(l=>l.articles.push(a));goto(`articles/${a.id}`);});return;}
    const a=state.articles.find(a=>a.id===id);if(!a){goto("articles");return;}
    view.innerHTML=`<a href="#/articles">← Letture</a><h2>Comprensione e traduzione</h2>${a.source_url?`<p><a href="${esc(a.source_url)}" target="_blank" rel="noopener">Apri la fonte originale</a></p>`:""}<div class="panel model" lang="en">${esc(a.text)}</div><label>La tua traduzione in italiano</label><textarea class="sheet" id="translation">${esc(a.translation)}</textarea><button id="compare">Confronta il significato</button>${a.feedback?`<h3>Cosa hai compreso</h3><p>${esc(a.feedback.overview_it)}</p>${a.feedback.segments.map(s=>`<section class="panel"><span class="tag">${{correct:"Compreso",partial:"Da precisare",incorrect:"Fraintendimento"}[s.understanding]}</span><p lang="en">${esc(s.source_quote)}</p><p>La tua versione: ${esc(s.user_quote)||"Passaggio omesso"}</p><p>Confronto: ${esc(s.translation_it)}</p><p class="small">${esc(s.explanation_it)}</p></section>`).join("")}<h3>Termini da recuperare</h3>${a.feedback.terms.map((t,i)=>`<section class="panel"><strong lang="en">${esc(t.term)}</strong><p>${esc(t.meaning_it)}</p><p>${esc(t.context_it)}</p><p lang="en">${esc(t.example_en)}</p><button class="ghost" data-article-term="${i}">Non lo conoscevo: usalo negli esercizi</button></section>`).join("")}<p>${esc(a.feedback.advice_it)}</p>`:""}`;
    $("#translation").oninput=e=>{const value=e.target.value;saveSoon(`${id}:translation`,l=>{l.articles.find(a=>a.id===id).translation=value;});};
    $("#compare").onclick=()=>act(async()=>{const current=(await load()).articles.find(a=>a.id===id);if(!current.translation.trim())throw new Error("Prova prima a tradurre il passaggio con parole tue.");const latest=await load();const p=await call("ARTICLE_FEEDBACK",{text:current.text,translation:current.translation,source_kind:current.source_kind,vocabulary_limit:learn.vocabularyLoad(latest),known_terms:[...VOCABULARY,...latest.vocabulary].filter(v=>latest.known.includes(v.id)).map(v=>v.expression)});await edit(l=>l.articles.find(a=>a.id===id).feedback=p);await refresh();});$$("[data-article-term]").forEach(b=>b.onclick=()=>addTerm(a.feedback.terms[+b.dataset.articleTerm],"articolo"));
  }
  async function progress(){const state=await load(),rows=learn.skillProgress(state.attempts),autonomous=state.writers.filter(w=>w.mode==="exam"&&w.feedback).length;view.innerHTML=`<h2>Progressi</h2><p class="muted">Riconoscere non equivale a usare bene una struttura nello scritto. Le risposte con aiuti e quelle ancora dubbie non aumentano il risultato autonomo.</p><table><thead><tr><th>Capacità</th><th>Corrette / valutate</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${skills[r.skill]}</td><td>${r.correct} / ${r.total}</td></tr>`).join("")}</tbody></table><p>${autonomous} scritti in simulazione revisionati; ${state.writers.filter(w=>w.mode==="guided").length} lavori guidati. ${state.known.length} termini segnati come conosciuti; ${state.reviews.length} carte di ripasso.</p><p>Carico proposto: ${learn.vocabularyLoad(state)} termini nuovi per blocco. Aumenta con più sessioni e risultati autonomi solidi, fino a 8; diminuisce se emergono difficoltà.</p><p class="small muted">Nessun livello STANAG assegnato automaticamente da questi conteggi. Una produzione guidata non dimostra trasferimento spontaneo.</p><a class="btn" href="#/learn">Continua</a>`;}
  function weekPlanHtml(p){if(!p?.sessions)return "";const days={mon:"Lunedì",tue:"Martedì",wed:"Mercoledì",thu:"Giovedì",fri:"Venerdì",sat:"Sabato"};return `<section class="panel"><h3>Piano personalizzato del tutor · ${esc(p.week_start)}</h3><ul>${p.sessions.map(s=>`<li>${days[s.day]||esc(s.day)}: ${esc(s.focus_it)}</li>`).join("")}</ul><p>${esc(p.rationale_it)}</p></section>`;}
  async function week(){const state=await load(),s=await getSettings(),lesson=learn.suggestedLesson(state,s.plan?.focus_tool);const agenda=["Ripasso + spiegazione + esercizi nuovi","Scrittura: consiglio, lessico e scaletta","Esercizi misti e produzione personale","Scrittura: stesura senza aiuti, se in simulazione","Ripasso differito + verifica","Revisione e riscrittura","Riposo o recupero"];
    view.innerHTML=`<h2>Piano settimanale</h2><p>Ogni sessione dura circa 20 minuti. Priorità suggerita: ${esc(lesson.title)}.</p><ul class="steps">${agenda.map((a,i)=>`<li><span class="dot">${i+1}</span><span>${a}</span><span class="small">${["lun","mar","mer","gio","ven","sab","dom"][i]}</span></li>`).join("")}</ul>${state.writers.filter(w=>w.type==="argument"&&w.stage<5).map(w=>{const second=new Date(Date.parse(w.created_at)+7*864e5);return `<section class="panel warn"><p>${esc(w.topic)}: il testo lungo occupa due settimane. Paragrafi 1–2 nella prima; 3–4 dalla settimana del ${second.toLocaleDateString("it-IT")}, poi revisione. Puoi anticipare se hai tempo.</p></section>`;}).join("")}${weekPlanHtml(s.week_plan)}<button id="weekly-ai" class="ghost">Proponi un piano personalizzato con il tutor</button><a class="btn" href="#/learn">Apri Studio</a>`;$("#weekly-ai").onclick=()=>act(async()=>{const date=new Date();date.setDate(date.getDate()-((date.getDay()+6)%7));await legacyRequest("WEEK_PLAN",{week_start:todayISO(date),capability:s.plan?.capability||"A2",focus_tool:s.plan?.focus_tool||"tenses",recent_errors:state.attempts.filter(a=>a.verdict==="incorrect").slice(-8),long_texts:state.writers.filter(w=>w.type==="argument"&&w.stage<5).map(w=>({task:w.prompt,split_across_weeks:true}))},{key:"WEEK_PLAN"});});}
  async function connect(){const s=await getSettings();view.innerHTML=`<h2>Tutor automatico</h2><p>GitHub ospita l'app; il Worker protegge la chiave Groq. Il tutor usa il modello configurato su Groq, non questa conversazione ChatGPT.</p><label>Indirizzo del Worker</label><input type="text" id="endpoint" placeholder="https://jflt-coach-tutor.NOME.workers.dev" value="${esc(s.ai_endpoint||"")}"><label>Codice personale del tutor (APP_TOKEN)</label><input type="password" id="token" autocomplete="off" placeholder="Non inserire qui la chiave Groq"><p class="small muted">Di default il codice resta nella sessione; puoi ricordarlo solo su un dispositivo personale. Non entra nei backup o nel codice pubblicato. Per restare gratuiti mantieni Workers Free e Groq Free: nessun fallback a pagamento è previsto nel codice.</p><label class="checkline"><input type="checkbox" id="remember-token"> Ricorda il codice su questo mio dispositivo (non usarlo su dispositivi condivisi)</label><label class="checkline"><input type="checkbox" id="consent"> Ho compreso che il tutor riceve i testi e il contesto necessari alla correzione. Uso dati fittizi, non informazioni operative riservate.</label><div class="row"><button id="save-connect">Salva e verifica il collegamento</button><button class="ghost" id="disconnect">Disconnetti</button></div><div id="connection-status"></div><p class="small">Se non è ancora pubblicato, segui <a href="SETUP.html" target="_blank" rel="noopener">le istruzioni di attivazione</a>. Le spiegazioni, il lessico e le bozze funzionano anche senza collegamento.</p>`;
    $("#save-connect").onclick=()=>act(async()=>{if(!$("#consent").checked)throw new Error("Conferma l'informativa prima di collegare il tutor.");const endpoint=workerUrl($("#endpoint").value.trim()),token=$("#token").value.trim();if(token.length<24)throw new Error("Il codice APP_TOKEN deve avere almeno 24 caratteri, come il segreto configurato sul Worker.");setAppToken(token,{remember:$("#remember-token").checked});const res=await fetch(`${endpoint}/health`,{headers:{Authorization:`Bearer ${token}`},credentials:"omit",cache:"no-store"});const p=await res.json();if(!res.ok||!p.ready){forgetToken();throw new Error(p.message||"Worker non pronto.");}const latest=await getSettings();latest.ai_endpoint=endpoint;await put("settings",latest);$("#token").value="";$("#connection-status").innerHTML='<div class="panel ok">Worker raggiungibile e codice accettato. La chiave Groq sarà verificata dalla prima generazione: prova una lezione.</div>';});$("#disconnect").onclick=async()=>{await flush();forgetToken();const latest=await getSettings();delete latest.ai_endpoint;await put("settings",latest);await refresh();};}
  async function render(path){const [a,b]=path.split("/");if(a==="learn")await dashboard();else if(a==="tenses")await tenseProgram();else if(a==="lesson")await lessonPage(b);else if(a==="practice")await practice(b);else if(a==="lexicon")await lexiconPage(b);else if(a==="review")await review();else if(a==="guided")await writerPage(b);else if(a==="articles")await articlesPage(b);else if(a==="progress")await progress();else if(a==="week")await week();else if(a==="connect")await connect();else return false;return true;}
  addEventListener("pagehide",()=>{flush().catch(()=>{});});
  return {render,flush};
}
