import test from "node:test";
import assert from "node:assert/strict";
import vm from "node:vm";
import {readFile,access} from "node:fs/promises";
import {APP_VERSION} from "../core.js";
const code=await readFile(new URL("../sw.js",import.meta.url),"utf8");
function runtime(){const listeners={},entries=new Map([["jflt-coach-0.1.2",new Map()],["other-app-cache",new Map()]]),shell=[],cache={open:async key=>{if(!entries.has(key))entries.set(key,new Map());const values=entries.get(key);return {addAll:async urls=>shell.push(...urls),match:async req=>values.get(typeof req==="string"?req:req.url),put:async(req,value)=>values.set(req.url,value)};},keys:async()=>[...entries.keys()],delete:async key=>entries.delete(key)};let network=0;vm.runInNewContext(code,{self:{registration:{scope:"https://example.test/Jflt-coach/"},addEventListener:(k,fn)=>listeners[k]=fn,skipWaiting:async()=>{},clients:{claim:async()=>{}}},caches:cache,URL,Response,fetch:async()=>{network++;throw new Error("offline");}});return {listeners,entries,shell,network:()=>network};}
test("service worker conserva le cache di altre app",async()=>{const r=runtime();let pending;r.listeners.install({waitUntil:p=>pending=p});await pending;r.listeners.activate({waitUntil:p=>pending=p});await pending;assert.ok(r.entries.has("other-app-cache"));assert.ok(!r.entries.has("jflt-coach-0.1.2"));for(const name of r.shell)await access(new URL(`../${name==="./"?"index.html":name}`,import.meta.url));});
test("service worker non intercetta il tutor o altre cartelle",()=>{const r=runtime();for(const request of [{method:"POST",url:"https://example.test/Jflt-coach/ai"},{method:"GET",url:"https://test.workers.dev/ai"},{method:"GET",url:"https://example.test/another-app/"}])r.listeners.fetch({request,respondWith(){assert.fail("Richiesta fuori ambito intercettata");}});});
test("navigazione offline usa solo la cache della versione attuale",async()=>{const r=runtime(),hit=new Response("current-version-shell");r.entries.set(`jflt-coach-${APP_VERSION}`,new Map([["index.html",hit]]));let pending;r.listeners.fetch({request:{method:"GET",url:"https://example.test/Jflt-coach/new-page",mode:"navigate"},respondWith:p=>pending=p});assert.equal(await (await pending).text(),"current-version-shell");assert.equal(r.network(),1);});
