import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {JSDOM} from "jsdom";
import {setAppToken} from "../ai-client.js";
import {validateBackup} from "../core.js";
import {freshLearning} from "../learning.js";
import {orderedQuestions,placementProfile} from "../placement.js";
const html=await readFile(new URL("../index.html",import.meta.url),"utf8");
const dom=new JSDOM(html,{url:"https://p7z4dm5cjz-ux.github.io/Jflt-coach/?selftest=1",pretendToBeVisual:true});
for(const [key,value] of Object.entries({window:dom.window,self:dom.window,document:dom.window.document,location:dom.window.location,sessionStorage:dom.window.sessionStorage,addEventListener:dom.window.addEventListener.bind(dom.window)}))Object.defineProperty(globalThis,key,{value,configurable:true,writable:true});
Object.defineProperty(globalThis,"navigator",{value:dom.window.navigator,configurable:true});dom.window.scrollTo=()=>{};
let calls=0,lastExerciseData;
globalThis.fetch=async(url,options)=>{
  if(String(url).endsWith("/health"))return Response.json({ready:true});
  calls++;const body=JSON.parse(options.body),d=body.data;let payload;
  if(body.mode==="EXERCISES"){lastExerciseData=d;payload={lesson_id:d.lesson.id,items:Array.from({length:d.n_items},(_,i)=>({id:`q${i}`,kind:d.exercise_plan[i].kind,skill:d.exercise_plan[i].skill,instruction_it:"Completa e spiega.",context_it:"Sono necessari elementi di prova.",stem:`${d.purpose==="check"?"Would we need":"We need"} ${d.exercise_plan[i].kind==="completion"?"___":"some evidence"} for case ${i}. The briefing mentions ${d.vocabulary[0].expression}. Topic: ${d.lesson.id}.`,answer:"some evidence",alternatives:["some evidence"],reason_it:"Quantità non specificata.",hints:["Pensa al nome.","Considera some information.","Evidence è non numerabile."],glosses:d.exercise_plan[i].kind==="completion"?[]:[{term:"evidence",meaning_it:"elementi di prova",context_it:"Elementi che sostengono un resoconto.",example_en:"The evidence supports the account."}],ambiguous:d.exercise_plan[i].kind==="production"}))};}
  else if(body.mode==="EVALUATE")payload={results:d.answers.map((a,i)=>({item_id:a.item_id,verdict:d.purpose==="check"&&i===0?"uncertain":"correct",issue:i===2?"style":"none",quote:a.user_answer,fix:i===2?"some supporting evidence":"",explanation_it:"Risposta accettabile nel contesto."})),advice_it:"Continua."};
  else if(body.mode==="WRITING_REVIEW")payload={priorities:["Chiarisci lo scopo.","Organizza i paragrafi."],errors:[{quote:"The team inspect the site yesterday",fix:"The team inspected the site yesterday",reason_it:"Yesterday richiede qui il passato.",kind:"error"}],rubric:{clarity:"Chiaro.",task:"Svolto.",organisation:"Da migliorare.",grammar:"Controllata.",lexis:"Pertinente."},rewrite_it:"Riscrivi mantenendo i fatti.",note:"Feedback didattico, non valutazione ufficiale JFLT."};
  else if(body.mode==="WRITING_MODEL")payload={model_en:"A comparison model based on your facts.",comparison_it:["Prima priorità.","Seconda priorità."],remaining_it:[]};
  else if(body.mode==="ARTICLE_FEEDBACK")payload={overview_it:"Significato confrontato.",segments:[{source_quote:d.text,user_quote:d.translation,translation_it:"Gli elementi di prova sostengono il resoconto del testimone.",explanation_it:"La traduzione conserva il significato.",understanding:"correct"}],terms:[{term:"evidence",meaning_it:"elementi di prova",context_it:"Sostegno a un resoconto.",example_en:"New evidence emerged."}],advice_it:"Ripassa evidence."};
  else throw new Error(`Unexpected test mode ${body.mode}`);
  return Response.json({request_id:body.request_id,mode:body.mode,payload,...(body.mode==="EXERCISES"?{warnings:["Alcune spiegazioni di vocaboli sono state omesse."]}:{})});
};
await import("../app.js");
async function until(fn){for(let i=0;i<150;i++){if(fn())return;await new Promise(r=>setTimeout(r,10));}throw new Error(`UI did not settle: ${document.getElementById("view").textContent.slice(0,120)}`);}
const api=window.__jflt;
await until(()=>document.querySelector("#view h2")?.textContent==="Oggi");
let settings=await api.get("settings","main");settings.ai_endpoint="https://test.workers.dev";settings.learning=freshLearning();await api.put("settings",settings);setAppToken("a-test-token-longer-than-24-characters");
async function visit(path,title){location.hash=`#/${path}`;await until(()=>document.querySelector("#view h2")?.textContent===title);}
function input(selector,value){const el=document.querySelector(selector);assert.ok(el,selector);el.value=value;el.dispatchEvent(new window.Event("input",{bubbles:true}));}
test("UI programma, lessico e connessione visibili",async()=>{await visit("learn","Studio");assert.ok(document.querySelectorAll(".lesson-list li").length>=43);assert.equal(document.querySelector("nav [aria-current=page]").dataset.tab,"learn");await visit("lexicon","Phrasal verbs e lessico");assert.equal(document.querySelector("nav [aria-current=page]").dataset.tab,"lexicon");input("#search","carry out");assert.ok(document.querySelector("#lex-results").textContent.includes("eseguire"));await visit("more","Altro");assert.ok(document.querySelector('#view a[href="#/requests"]'));await visit("connect","Tutor automatico");assert.ok(document.querySelector("#token"));assert.equal(document.querySelector("#token").value,"");});
test("UI genera esercizi, apre glossario, salva risposte e corregge",async()=>{await visit("lesson/some-any","Some, any, no e composti");document.querySelector("#generate").click();await until(()=>document.querySelector("#view h2")?.textContent==="Esercitazione");assert.equal(document.querySelectorAll("[data-answer]").length,6);document.querySelector("[data-gloss]").click();await until(()=>!!document.querySelector("[data-learn-word]"));document.querySelector("[data-learn-word]").click();await until(()=>document.querySelector(".toast")?.textContent.includes("Termine salvato"));for(const el of document.querySelectorAll("[data-answer]"))input(`[data-answer="${el.dataset.answer}"]`,"some evidence");document.querySelector("#evaluate").click();await until(()=>document.querySelectorAll(".panel.ok strong").length===6);const state=(await api.get("settings","main")).learning;assert.ok(document.getElementById("view").textContent.includes("Alternativa di stile: some supporting evidence"));assert.equal(state.attempts.length,6);assert.equal(state.attempts.filter(a=>a.assisted).length,1);assert.ok(state.reviews.some(r=>r.front.includes("evidence")));});
test("UI simulazione nasconde aiuti e blocca consegna incompleta",async()=>{await visit("lesson/some-any","Some, any, no e composti");document.querySelector("#test").click();await until(()=>document.querySelector("#view h2")?.textContent==="Verifica senza aiuti");assert.equal(document.querySelectorAll("[data-hint],[data-gloss]").length,0);input('[data-answer="q0"]',"some evidence");const before=calls;document.querySelector("#evaluate").click();await until(()=>document.querySelector(".panel.err")?.textContent.includes("Completa tutte"));assert.equal(calls,before);for(const el of document.querySelectorAll("[data-answer]"))input(`[data-answer="${el.dataset.answer}"]`,"some evidence");document.querySelector("#evaluate").click();await until(()=>!!document.querySelector("[data-answer][readonly]"));assert.equal(document.querySelector("#evaluate"),null);assert.ok(document.querySelector(".panel.warn strong").textContent.includes("Da valutare"));});
test("UI scrittura guidata salva e sblocca il modello solo dopo riscrittura",async()=>{await visit("guided/new","Scrittura passo passo");input("#topic","Report on a routine inspection.");document.querySelector("#start-writing").click();await until(()=>document.querySelector("#view h2")?.textContent==="Consiglio e idee");assert.equal(document.querySelector("nav [aria-current=page]").dataset.tab,"write");assert.ok(document.querySelector('#view a[href="#/guided/new"]'));assert.equal(document.querySelectorAll(".writing-track li").length,7);assert.ok(document.querySelector(".writing-track [aria-current=step]").textContent.includes("Consiglio e idee"));input("#ideas","Explain where the team went and what it checked.");document.querySelector("#next").click();await until(()=>document.querySelector("#view h2")?.textContent==="Lessico");assert.ok(document.querySelectorAll("[data-term-keep]").length>=3);document.querySelector("#next").click();await until(()=>document.querySelector("#view h2")?.textContent==="Scaletta");input("#outline","Purpose\nFacts\nActions\nConclusion");document.querySelector("#next").click();await until(()=>document.querySelector("#view h2")?.textContent==="Paragrafi");for(let i=0;i<4;i++)input(`[data-paragraph="${i}"]`,"The team inspect the site yesterday and checked the available records before returning to the base.");document.querySelector("#review-writing").click();await until(()=>document.querySelector("#view h2")?.textContent==="Riscrittura");assert.equal(document.querySelectorAll("h3").length>=1,true);document.querySelector("[data-error-review]").click();await until(()=>document.querySelector(".toast")?.textContent.includes("Errore salvato"));const before=calls;document.querySelector("#model").click();await until(()=>document.querySelector(".panel.err")?.textContent.includes("riscrittura"));assert.equal(calls,before);input("#rewrite","The team completed the inspection and recorded its findings before returning to the base.");document.querySelector("#model").click();await until(()=>document.querySelector("#view h2")?.textContent==="Confronto");assert.ok(document.querySelector(".model").textContent.includes("comparison model"));});
test("UI articolo tradotto dopo la prova, termini recuperabili e backup valido",async()=>{await visit("articles","Leggere e tradurre");input("#article-text","The evidence supports the witness account.");document.querySelector("#start-article").click();await until(()=>document.querySelector("#view h2")?.textContent==="Comprensione e traduzione");const before=calls;document.querySelector("#compare").click();await until(()=>document.querySelector(".panel.err")?.textContent.includes("tradurre"));assert.equal(calls,before);input("#translation","Gli elementi di prova sostengono la versione del testimone.");document.querySelector("#compare").click();await until(()=>!!document.querySelector("[data-article-term]"));document.querySelector("[data-article-term]").click();await until(()=>document.querySelector(".toast")?.textContent.includes("Termine salvato"));const stores={};for(const name of ["settings","diag_responses","diag_texts","profile","requests","grammar_sets","grammar_answers","tasks","texts","feedback","error_log","cards","transfer_checks","device_tests","to_verify"])stores[name]=await api.all(name);const result=validateBackup({format:"jflt-coach-backup/v1",app_version:"0.2.0",exported_at:new Date().toISOString(),stores});assert.deepEqual(result.errors,[]);});
test("UI tempi verbali raggiungibili da Oggi e generazione sul tempo selezionato",async()=>{
  await visit("home","Oggi");const link=document.querySelector('#view a[href="#/tenses"]');assert.ok(link);link.click();await until(()=>document.querySelector("#view h2")?.textContent==="Tempi verbali");assert.equal(document.querySelector("nav [aria-current=page]").dataset.tab,"learn");assert.equal(document.querySelectorAll(".tense-group li").length,15);
  document.querySelector('#view a[href="#/lesson/present-perfect-continuous"]').click();await until(()=>document.querySelector("#view h2")?.textContent==="Present perfect continuous");assert.match(document.getElementById("view").textContent,/have\/has been/);document.querySelector("#generate").click();await until(()=>document.querySelector("#view h2")?.textContent==="Esercitazione");assert.equal(lastExerciseData.lesson.id,"present-perfect-continuous");assert.equal(lastExerciseData.exercise_plan.length,6);assert.deepEqual(lastExerciseData.exercise_plan.map(p=>p.kind),["meaning","completion","error_correction","transformation","context_switch","production"]);assert.ok(lastExerciseData.session_seed);assert.equal(document.querySelectorAll("[data-answer]").length,6);assert.ok([...document.querySelectorAll(".stem")].some(p=>p.textContent.includes("___")));
  const state=(await api.get("settings","main")).learning;assert.ok(state.sets.some(s=>s.lesson_id==="present-perfect-continuous"));
});
test("UI pre-test offline: 45 risposte, ripresa, niente soluzioni, priorità e backup",async()=>{
  await visit("home","Oggi");assert.ok(document.querySelector('#view a[href="#/placement"]'));await visit("placement","Pre-test di ingresso");const before=calls;document.querySelector("#placement-start").click();await until(()=>!!document.querySelector("#placement-next"));
  const p=(await api.get("settings","main")).learning.placement,order=orderedQuestions(p.seed);
  // Una risposta cancellata deve essere cancellata anche dal salvataggio.
  const firstTyped=order.findIndex(q=>!q.options);
  for(let i=0;i<45;i++){
    const q=order[i];await until(()=>document.querySelector('#view .eyebrow')?.textContent===`Domanda ${i+1} di 45`);assert.equal(document.querySelectorAll("[data-gloss],[data-hint]").length,0);assert.equal(document.getElementById("view").textContent.includes("Risposta di riferimento:"),false);
    if(q.options){const el=[...document.querySelectorAll('input[name="placement-answer"]')].find(el=>el.value===q.answer);el.checked=true;el.dispatchEvent(new window.Event("input",{bubbles:true}));}
    else input("#placement-answer",q.id==="P02"?"carry out it":q.answer);
    input("#placement-confidence","sure");
    if(i===firstTyped){input("#placement-answer","");await new Promise(r=>setTimeout(r,10));assert.ok(!(await api.get("settings","main")).learning.placement.answers.some(a=>a.id===q.id));input("#placement-answer",q.id==="P02"?"carry out it":q.answer);}
    if(i===15){await visit("home","Oggi");assert.ok(document.querySelector('#view a[href="#/placement/run"]'));await visit("placement/run","Pre-test di ingresso");await until(()=>!!document.querySelector("#placement-next"));}
    document.querySelector("#placement-next").click();
  }
  await until(()=>document.querySelector("#view h2")?.textContent==="Consegna il pre-test");assert.equal(calls,before);assert.equal(document.getElementById("view").textContent.includes("Risposta di riferimento:"),false);document.querySelector("#placement-submit").click();await until(()=>document.querySelector("#view h2")?.textContent==="Risultato del pre-test");assert.ok(document.querySelector('#view a[href="#/lesson/phrasal-basics"]'));assert.ok(document.getElementById("view").textContent.includes("carry it out"));
  const settings=await api.get("settings","main"),profile=placementProfile(settings.learning.placement);assert.equal(profile.correct,44);assert.equal(profile.lessonStatus.sentence,"skip");assert.equal(profile.lessonStatus.pronouns,"skip");assert.ok(settings.learning.reviews.some(r=>r.front.startsWith("carry out:")));
  const stores={};for(const name of ["settings","diag_responses","diag_texts","profile","requests","grammar_sets","grammar_answers","tasks","texts","feedback","error_log","cards","transfer_checks","device_tests","to_verify"])stores[name]=await api.all(name);assert.deepEqual(validateBackup({format:"jflt-coach-backup/v1",app_version:"0.2.4",exported_at:new Date().toISOString(),stores}).errors,[]);
  await visit("learn","Studio");assert.ok(document.getElementById("view").textContent.includes("Rivedi il pre-test: 44/45"));
});
