// Pre-test originale: selezione del percorso, non certificazione CEFR/STANAG.
export const BANK_VERSION = "2026-10-08-v1";
export const AREAS = {
  tenses:"Tempi verbali", negatives:"Negazioni e domande", phrasals:"Phrasal verbs",
  basics:"Controllo delle basi", quantifiers:"Nomi e quantificatori", modals:"Modali",
  clauses:"Frasi complesse", patterns:"Costruzioni e connettivi"
};
export const PHRASAL_TARGETS={P01:"carry out",P02:"carry out",P03:"look into",P04:"look into",P05:"call off",P06:"run out of",P07:"put up with",P08:"rule out"};
const q=(id,area,lessons,skill,stem,options,answer,why,ref,accept=[])=>({id,area,lessons:lessons.split(" "),skill,stem,options,answer,accept:[answer,...accept],why,ref});
export const QUESTIONS = [
  q("T01","tenses","present-simple present","choose","Parli di un'abitudine: The officer ___ identification documents every morning.",["checks","is checking","has checked"],"checks","Every morning descrive la routine; il soggetto singolare richiede -s.","OXFORD unità 5, p. 24"),
  q("T02","tenses","present-continuous present","form","Usa il present continuous di interview: The officers ___ a witness right now.",null,"are interviewing","Un'attività in corso: are + verbo in -ing; officers è plurale.","OXFORD unità 9, p. 32"),
  q("T03","tenses","past-simple perfect-simple","choose","Scegli la frase standard per un evento concluso ieri.",["We received the statement yesterday.","We have received the statement yesterday.","We had receive the statement yesterday."],"We received the statement yesterday.","Yesterday colloca l'evento in un periodo finito: past simple.","OXFORD unità 28, p. 74"),
  q("T04","tenses","past-continuous past","form","Usa il past continuous di patrol per l'attività in corso: We ___ the district when the radio call came in.",null,"were patrolling","L'attività di sfondo era in corso quando è arrivata la chiamata: were + -ing.","OXFORD unità 22, p. 60; CAMPAIGN p. 51"),
  q("T05","tenses","present-perfect-simple perfect-simple","choose","Parli del risultato attuale senza indicare un momento passato finito: The investigator ___ the missing file, so we can use it now.",["has found","has find","is find"],"has found","Has + participio: found. Il contesto mette in primo piano il risultato presente.","OXFORD unità 25, p. 68"),
  q("T06","tenses","present-perfect-continuous perfect-continuous","form","Usa il present perfect continuous di wait: We ___ for the interpreter for two hours, and we are still waiting.",null,"have been waiting","Attività iniziata prima e ancora in corso: have been + -ing.","OXFORD unità 30, p. 78",["'ve been waiting"]),
  q("T07","tenses","past-perfect-simple past-perfect","choose","Il veicolo era già partito prima del nostro arrivo: When we reached the checkpoint, the vehicle ___.",["had already left","has already left","had already leave"],"had already left","Il riferimento è un altro momento passato: had + participio per l'anteriorità.","OXFORD unità 33, p. 84"),
  q("T08","tenses","past-perfect-continuous past-perfect","form","Usa il past perfect continuous di drive: At the end of yesterday's journey, she was tired because she ___ for six hours.",null,"had been driving","Durata dell'attività prima di un momento passato: had been + -ing.","OXFORD unità 34, p. 86",["'d been driving"]),
  q("T09","tenses","future-will future","choose","La decisione viene presa mentre parli: 'The printer has stopped.' 'All right, I ___ IT now.'",["will call","will calling","will to call"],"will call","Will + forma base può esprimere una decisione presa in quel momento.","OXFORD unità 39, p. 98"),
  q("T10","tenses","future-going-to future","form","Usa be going to + inspect per un piano: They ___ the premises tomorrow.",null,"are going to inspect","Piano futuro: be concordato con il soggetto + going to + forma base.","OXFORD unità 38, p. 96",["'re going to inspect"]),
  q("T11","tenses","future-arrangements future","choose","Un incontro è già concordato. Quale frase usa il present continuous con valore futuro?",["We are meeting the liaison officer at ten tomorrow.","We meeted the liaison officer at ten tomorrow.","We have meeting the liaison officer at ten tomorrow."],"We are meeting the liaison officer at ten tomorrow.","Are meeting può descrivere l'accordo futuro. Anche going to può essere adatto, ma qui è richiesta la forma continuous.","OXFORD unità 37, p. 94"),
  q("T12","tenses","future-continuous future-perfect","form","Usa il future continuous di brief: At this time tomorrow, the commander ___ the team.",null,"will be briefing","Attività in corso in un preciso momento futuro: will be + -ing.","OXFORD unità 42, p. 104",["'ll be briefing"]),
  q("T13","tenses","future-perfect-simple future-perfect","form","Usa il future perfect simple di finish: By the time the next shift starts, we ___ the report.",null,"will have finished","Completamento entro un riferimento futuro: will have + participio.","OXFORD unità 42, pp. 104-105",["'ll have finished"]),
  q("T14","tenses","future-perfect-continuous","choose","Quale forma mette a fuoco la durata dell'attività fino a un momento futuro? By next June, she ___ here for two years.",["will have been working","will have working","will be been working"],"will have been working","Will have been + -ing sottolinea la durata fino al riferimento futuro.","OXFORD unità 42, p. 104, sezione F"),
  q("N01","negatives","negatives questions present-simple","form","Rendi negativa l'abitudine; completa solo la lacuna: She ___ night shifts. (work)",null,"does not work","Doesn't/does not porta la -s: il verbo principale torna alla forma base.","OXFORD unità 5, p. 24",["doesn't work"]),
  q("N02","negatives","negatives questions past-simple","form","Completa la negativa al passato: We ___ the vehicle yesterday. (stop)",null,"did not stop","Dopo did not/didn't si usa stop, non stopped.","OXFORD unità 18, p. 52",["didn't stop"]),
  q("N03","negatives","negatives questions","choose","Scegli la negativa corretta di be.",["The witnesses were not present.","The witnesses did not were present.","The witnesses were not be present."],"The witnesses were not present.","Be prende not direttamente; non si aggiunge did.","OXFORD unità 16, p. 48"),
  q("N04","negatives","negatives questions present-perfect-simple","form","Usa il present perfect negativo di receive: We ___ the documents yet.",null,"have not received","Not segue l'ausiliare have; il verbo resta al participio received.","OXFORD unità 25, p. 68",["haven't received"]),
  q("N05","negatives","negatives questions ability","choose","Quale negativa di un modale è corretta?",["She cannot attend the briefing.","She does not can attend the briefing.","She cannot to attend the briefing."],"She cannot attend the briefing.","Il modale riceve la negazione direttamente e regge la forma base senza to.","OXFORD unità 54, p. 132"),
  q("N06","negatives","negatives some-any","choose","Esprimi in inglese standard che nessuno dei testimoni ha visto l'auto.",["None of the witnesses saw the car.","None of the witnesses didn't see the car.","Nobody of the witnesses saw the car."],"None of the witnesses saw the car.","None contiene già la negazione; non si aggiunge didn't per lo stesso significato.","OXFORD unità 115, p. 266"),
  q("N07","negatives","questions negatives","form","Completa la domanda negativa: Why ___ report the incident yesterday? (he / not)",null,"did he not","Ordine non contratto: did + soggetto + not. Nella forma contratta: didn't he.","OXFORD unità 67, p. 160",["didn't he"]),
  q("N08","negatives","indirect-questions questions","choose","Quale domanda indiretta è corretta?",["Could you tell me where the entrance is?","Could you tell me where is the entrance?","Could you tell me where does the entrance is?"],"Could you tell me where the entrance is?","Nella parte indiretta l'ordine è soggetto + verbo; l'inversione è nella principale Could you.","OXFORD unità 70, p. 168; MISSION pp. 80-82"),
  q("P01","phrasals","phrasal-basics","choose","In 'The officers carried out an inspection', carried out significa:",["hanno eseguito","hanno rinviato","hanno abbandonato"],"hanno eseguito","Carry out + attività indica svolgerla o eseguirla, anche in contesti professionali.","OXFORD unità 136, p. 308; MISSION p. 33"),
  q("P02","phrasals","phrasal-basics","form","Sostituisci the inspection con it: The team will carry out the inspection. Scrivi solo le tre parole dopo will.",null,"carry it out","Carry out in questo uso è separabile: il pronome oggetto va nel mezzo.","OXFORD unità 136, p. 308"),
  q("P03","phrasals","phrasal-basics","choose","In 'We will look into the complaint', look into significa:",["esaminare o approfondire","guardare fisicamente dentro una scatola","annullare"],"esaminare o approfondire","Look into qui significa indagare una questione; non separare verbo e preposizione.","OXFORD unità 136, p. 308; MISSION p. 33"),
  q("P04","phrasals","phrasal-basics","choose","Scegli la costruzione corretta con il pronome it.",["We will look into it.","We will look it into.","We will look into to it."],"We will look into it.","Look into è inseparabile in questo significato: l'oggetto segue l'espressione.","OXFORD unità 136, p. 308"),
  q("P05","phrasals","phrasal-basics","choose","The exercise was called off because of severe weather. Che cosa è successo?",["L'esercitazione è stata annullata.","L'esercitazione è iniziata.","L'esercitazione è stata descritta al telefono."],"L'esercitazione è stata annullata.","Call off significa annullare; l'espressione è al passivo was called off.","OXFORD unità 136, p. 308; applicazione originale"),
  q("P06","phrasals","phrasal-basics","form","Completa con le due particelle mancanti: We have run ___ ___ time.",null,"out of","Run out of significa esaurire una disponibilità: il complemento segue out of.","OXFORD unità 137, p. 310"),
  q("P07","phrasals","phrasal-basics","choose","Quale costruzione significa 'tollerare questo comportamento'?",["put up with this behaviour","put this behaviour up with","put up this behaviour with"],"put up with this behaviour","Put up with è un'espressione in tre parti; il complemento viene dopo with.","OXFORD unità 137, p. 310"),
  q("P08","phrasals","phrasal-basics","choose","The team ruled out an electrical fault. Il guasto elettrico è stato:",["escluso come spiegazione","confermato come spiegazione","segnalato per la prima volta"],"escluso come spiegazione","Rule out indica escludere una possibilità sulla base degli elementi disponibili.","Applicazione lessicale originale; costruzioni OXFORD unità 136"),
  q("B01","basics","pronouns","choose","Quale frase distingue correttamente soggetto e oggetto?",["She asked him to wait.","Her asked he to wait.","Hers asked his to wait."],"She asked him to wait.","She è pronome soggetto; him è pronome complemento.","OXFORD unità 120, p. 276"),
  q("B02","basics","sentence adjectives","choose","Quale frase ha il normale ordine dichiarativo?",["The officer carefully checked the document.","Checked the document the officer carefully.","The document carefully the officer checked."],"The officer carefully checked the document.","Il normale ordine è soggetto, verbo, oggetto; carefully modifica checked.","OXFORD The basics, pp. 10-13; unità 150"),
  q("B03","basics","sentence present-simple","form","Completa al present simple di check: The officers ___ the equipment before every shift.",null,"check","Officers è plurale: forma base check, senza -s. La -s si usa con he/she/it.","OXFORD unità 5, p. 24"),
  q("Q01","quantifiers","nouns quantifiers","choose","Il nome evidence è non numerabile in questo uso. Scegli la frase standard.",["We do not have much evidence.","We do not have many evidences.","We do not have an evidence."],"We do not have much evidence.","Much si combina con nomi non numerabili; si può dire a piece of evidence per un singolo elemento.","OXFORD unità 106, p. 248; unità 116, p. 268"),
  q("Q02","quantifiers","some-any","choose","Stai offrendo assistenza: Would you like ___ help with the form?",["some","no","every"],"some","Some è frequente in offerte e richieste orientate a una risposta positiva, anche se sono domande.","OXFORD unità 114, p. 264"),
  q("Q03","quantifiers","some-any quantifiers","choose","Indica che nessuno dei due rapporti è completo: ___ report is complete.",["Neither","Both","Every of"],"Neither","Neither + nome singolare si riferisce a nessuno di due; both richiede nome plurale.","OXFORD unità 118, p. 272"),
  q("M01","modals","obligation negatives","choose","La comunicazione vieta di entrare. You ___ enter this room.",["must not","do not have to","need not"],"must not","Must not indica divieto; do not have to e need not indicano assenza di obbligo.","OXFORD unità 55, p. 134; unità 57, p. 138"),
  q("M02","modals","may-might","choose","Non sai se il testimone arriverà. Esprimi una possibilità, non una certezza.",["The witness might arrive later.","The witness must arrived later.","The witness might to arrive later."],"The witness might arrive later.","Might + forma base esprime possibilità; non ha to né desinenze del passato.","OXFORD unità 59, p. 142"),
  q("M03","modals","deduction","choose","La porta è ancora sigillata: deduci che non è entrato da lì. He ___ through that door.",["cannot have entered","must not have enter","cannot entered"],"cannot have entered","Cannot/can't have + participio esprime una deduzione negativa su un evento passato.","OXFORD unità 59, pp. 142-143",["can't have entered"]),
  q("C01","clauses","conditionals-unreal","choose","Il controllo non è stato fatto, quindi l'errore non è stato trovato: If we ___ the file, we would have found the error.",["had checked","would have checked","have checked"],"had checked","Ipotesi contraria al passato: if + past perfect; nella principale would have + participio.","OXFORD unità 103, p. 240; applicate le errata MISSION/TARGET"),
  q("C02","clauses","passive","choose","Il rapporto è stato approvato ieri. Scegli il passivo corretto.",["The report was approved yesterday.","The report was approve yesterday.","The report has approved yesterday."],"The report was approved yesterday.","Passivo passato: was/were + participio. Il soggetto riceve l'azione.","OXFORD unità 47, p. 116"),
  q("C03","clauses","relatives","choose","Quale frase identifica il testimone che ha dato la dichiarazione?",["The witness who gave the statement has left.","The witness which gave the statement has left.","The witness who he gave the statement has left."],"The witness who gave the statement has left.","Who si riferisce a una persona e fa da soggetto nella relativa: non si ripete he.","OXFORD unità 157, p. 354"),
  q("R01","patterns","verb-patterns prepositions","choose","Completa l'email: We look forward to ___ from you.",["hearing","hear","heard"],"hearing","In look forward to, to è una preposizione: segue il gerundio, non l'infinito.","OXFORD unità 80, p. 190; MISSION p. 33"),
  q("R02","patterns","linkers clauses cohesion","choose","Quale frase collega correttamente due proposizioni indipendenti con however?",["The road was closed; however, the team found another route.","The road was closed, however the team found another route.","Although the road was closed, however the team found another route."],"The road was closed; however, the team found another route.","However non lega le due proposizioni come but: servono punto o punto e virgola; evita although insieme a however per lo stesso collegamento.","OXFORD unità 165, pp. 372-373; TARGET pp. 14-18, con errata"),
  q("R03","patterns","verb-patterns","choose","Il senso è 'si è fermato per parlare': The officer stopped ___ to the witness.",["to talk","talking","talk"],"to talk","Stop to talk descrive lo scopo della sosta; stop talking significa smettere di parlare.","OXFORD unità 77, p. 184")
];
const norm=value=>String(value??"").normalize("NFKC").toLowerCase().replace(/[’‘]/g,"'").replace(/[.!?]+$/g,"").replace(/\s+/g," ").trim();
export function isCorrect(item,value){return item.accept.some(a=>norm(a)===norm(value));}
function hash(s){let h=2166136261;for(const c of s){h^=c.charCodeAt(0);h=Math.imul(h,16777619);}return h>>>0;}
export function orderedQuestions(seed){return QUESTIONS.slice().sort((a,b)=>hash(seed+a.id)-hash(seed+b.id));}
export function orderedOptions(item,seed){return (item.options||[]).slice().sort((a,b)=>hash(seed+item.id+a)-hash(seed+item.id+b));}
export function newPlacement(seed=crypto.randomUUID(),now=new Date().toISOString()){
  return {version:1,bank_version:BANK_VERSION,seed,answers:[],position:0,started_at:now,submitted_at:null};
}
export function validPlacement(p){
  if(!p||p.version!==1||p.bank_version!==BANK_VERSION||typeof p.seed!=="string"||!p.seed||p.seed.length>100||!Array.isArray(p.answers)||p.answers.length>45||!Number.isInteger(p.position)||p.position<0||p.position>=45||!Number.isFinite(Date.parse(p.started_at))||(p.submitted_at!==null&&!Number.isFinite(Date.parse(p.submitted_at))))return false;
  if(Object.keys(p).some(k=>!["version","bank_version","seed","answers","position","started_at","submitted_at"].includes(k)))return false;
  const ids=new Set();for(const a of p.answers){const item=QUESTIONS.find(q=>q.id===a?.id);if(!item||ids.has(a.id)||typeof a.value!=="string"||a.value.length>350||!["sure","unsure"].includes(a.confidence)||Object.keys(a).some(k=>!["id","value","confidence"].includes(k))||(item.options&&a.value&&!item.options.includes(a.value)))return false;ids.add(a.id);}
  return p.submitted_at===null||p.answers.length===45;
}
export function placementProfile(p){
  if(!validPlacement(p)||!p.submitted_at)return null;
  const rows=QUESTIONS.map(item=>{const answer=p.answers.find(a=>a.id===item.id);return {item,answer,correct:isCorrect(item,answer.value),secure:answer.confidence==="sure"&&isCorrect(item,answer.value)};});
  const areas=Object.entries(AREAS).map(([id,title])=>{const tests=rows.filter(r=>r.item.area===id),correct=tests.filter(r=>r.correct).length,secure=tests.filter(r=>r.secure).length;return {id,title,total:tests.length,correct,secure,unknown:tests.filter(r=>!r.answer.value).length,rate:correct/tests.length,status:secure/tests.length>=0.85?"skip":correct/tests.length>=0.7?"confirm":"review"};});
  const lessons={};for(const row of rows)for(const id of row.item.lessons){(lessons[id]??=[]).push(row);}
  const lessonStatus={};for(const [id,tests] of Object.entries(lessons)){const secure=tests.every(r=>r.secure);lessonStatus[id]=tests.some(r=>!r.correct)?"review":secure&&tests.length>=2&&new Set(tests.map(r=>r.item.skill)).size>=2?"skip":"confirm";}
  // Un controllo corretto di soggetto/oggetto permette di lasciare il corso base.
  if(rows.filter(r=>r.item.area==="basics").every(r=>r.secure)){lessonStatus.sentence="skip";lessonStatus.pronouns="skip";}
  const errors=rows.filter(r=>!r.correct);
  const priorityIds=[...new Set(errors.flatMap(r=>r.item.lessons))];
  const weight=id=>rows.filter(r=>r.item.lessons.includes(id)&&!r.correct).reduce((sum,r)=>sum+(["tenses","negatives","phrasals"].includes(r.item.area)?2:1),0);
  priorityIds.sort((a,b)=>weight(b)-weight(a));
  return {correct:rows.filter(r=>r.correct).length,total:45,areas,lessonStatus,priorityIds,errors,uncertain:rows.filter(r=>r.correct&&!r.secure),rows};
}
