import {readFile,writeFile} from "node:fs/promises";
import {LESSONS} from "../catalog.js";
import {bookContext} from "../bookshelf.js";
import {VERSION,API_VERSION} from "../engine.js";
const root=new URL("../",import.meta.url);
const contract=(await readFile(new URL("contract.js",root),"utf8")).replaceAll("export ","");
const runtime=await readFile(new URL("worker/runtime.js",root),"utf8");
const contexts=Object.fromEntries(LESSONS.map(l=>[l.id,{lesson:l,books:bookContext(l.id)}]));
const writing=Object.fromEntries(["report","email","argument"].map(type=>[type,bookContext("","WRITING_REVIEW",type)]));
const code="// Generated by npm run build:worker. Standalone Cloudflare entrypoint.\nconst VERSION="+JSON.stringify(VERSION)+";\nconst API_VERSION="+API_VERSION+";\nconst LESSON_CONTEXT="+JSON.stringify(contexts)+";\nconst WRITING_CONTEXT="+JSON.stringify(writing)+";\nconst READING_CONTEXT="+JSON.stringify(bookContext("","ARTICLE_FEEDBACK"))+";\n"+contract+"\n"+runtime;
if(process.argv.includes("--check")){if(await readFile(new URL("worker/index.js",root),"utf8")!==code)throw new Error("Worker non aggiornato: esegui npm run build:worker.");console.log("Worker, contratto e contenuti sincronizzati.");}
else{await writeFile(new URL("worker/index.js",root),code);console.log("Worker "+VERSION+" generato.");}
